# First Script: Creating the Meta-DataFrame
In this script the author analyzes each column of the synthetic BPI_C 2019 event logs.

In [1]:
#import libraries
import json
import os
import pandas as pd
import numpy
import re

In [2]:
event_log_name = 'BPIC_Synthetic_Split_2' #addd the name of the event log - change for each event log
event_log_file_path = f'event_logs/{event_log_name}.csv' #string interpolation, one has to create a folder called 'event_logs' to import the event log.csv
print(event_log_file_path) # review the path

event_logs/BPIC_Synthetic_Split_2.csv

In [3]:
#import the event log
event_log_table = pd.read_csv(event_log_file_path) #optionally this can be added; header = 0, encoding = 'ISO-8859-1') if encoding issues arise
event_log_table.head(20) #view the first 20 rows

/var/folders/vz/snd73j8d2mj817493bt9ykfc0000gn/T/ipykernel_63845/3280910462.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  event_log_table = pd.read_csv(event_log_file_path) #optionally this can be added; header = 0, encoding = 'ISO-8859-1') if encoding issues arise

,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,case Item Category,case Spend classification text,case Source,...,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event concept:name,event Cumulative net worth (EUR),event time:timestamp,caseID
0,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
1,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,30957.0,Mar 14 2018 03:11:00,4507016139 1
2,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,1157.0,Mar 14 2018 03:11:00,4507016139 1
3,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,2386.0,Mar 14 2018 03:11:00,4507016139 1
4,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
5,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
6,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
7,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
8,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
9,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
10,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
11,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,21699.0,Mar 14 2018 03:13:00,4507016139 1
12,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,144.0,Mar 14 2018 03:13:00,4507016139 1
13,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:13:00,4507016139 1
14,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:13:00,4507016139 1
15,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:14:00,4507016139 1
16,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:14:00,4507016139 1
17,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:15:00,4507016139 1
18,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,19239.0,Mar 14 2018 03:15:00,4507016139 1
19,2.270000e+14,Logistics,Standard PO,Road Packed,NaN,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,17937.0,Mar 14 2018 03:16:00,4507016139 1

In [4]:
#review changes on the last column
event_log_table

,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,case Item Category,case Spend classification text,case Source,...,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event concept:name,event Cumulative net worth (EUR),event time:timestamp,caseID
0,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
1,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,30957.0,Mar 14 2018 03:11:00,4507016139 1
2,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,1157.0,Mar 14 2018 03:11:00,4507016139 1
3,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,batch_07,batch_07,Record Goods Receipt,2386.0,Mar 14 2018 03:11:00,4507016139 1
4,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507016139_00001,True,NaN,NaN,Record Service Entry Sheet,72.0,Mar 14 2018 03:11:00,4507016139 1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349521,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507032138_00001,True,NaN,NaN,Record Service Entry Sheet,13.0,May 29 2018 00:53:00,4507032138 1
349522,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507032138_00001,True,NaN,NaN,Record Service Entry Sheet,13.0,May 29 2018 00:53:00,4507032138 1
349523,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507032138_00001,True,NaN,NaN,Record Service Entry Sheet,13.0,May 29 2018 00:53:00,4507032138 1
349524,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507032138_00001,True,NaN,NaN,Record Service Entry Sheet,13.0,May 29 2018 00:53:00,4507032138 1
349525,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,"Three way match, invoice after GR",NPR,sourceSystemID_0000,...,1,1,4507032138_00001,True,NaN,NaN,Record Service Entry Sheet,13.0,May 29 2018 00:53:00,4507032138 1

In [5]:
#Review all og the event log columns, to decide which ones are mandatory and which ones are additional

log_columns = event_log_table.columns
log_columns # this variable is important for the Meta-DataFrame generation

Index(['eventID ', 'case Spend area text', 'case Document Type',
       'case Sub spend area text', 'case Purch. Doc. Category name',
       'case Vendor', 'case Item Type', 'case Item Category',
       'case Spend classification text', 'case Source', 'case Name',
       'case GR-Based Inv. Verif.', 'case Item', 'case concept:name',
       'case Goods Receipt', 'event User', 'event org:resource',
       'event concept:name', 'event Cumulative net worth (EUR)',
       'event time:timestamp', 'caseID'],
      dtype='object')

In [6]:
# This has to be tailored to each event log
#caseID is created from 'C_Purchasing Document' and 'case Item', define the mandatory columns based on domain knowledge analysis

mandatory_columns = ['caseID', 'event time:timestamp', 'event concept:name', 'eventID ']

#Create an object/dictionary and corresponding key:value pairs to add the semantic titles which the csv titles represent in a variable  which are relevant for the Meta-DataFrame
titles = {
  'caseID': 'Case ID',
  'event concept:name': 'Activity',
  'event_ID ': 'Event ID',
  'event time:timestamp': 'Timestamp',
}

print(mandatory_columns)

['caseID', 'event time:timestamp', 'event concept:name', 'eventID ']

In [7]:
#Review titles object which are relevant for the Meta-DataFrame
titles

{'caseID': 'Case ID',
 'event concept:name': 'Activity',
 'event_ID ': 'Event ID',
 'event time:timestamp': 'Timestamp'}

In [8]:
#Review the datatypes for datatype harmonization
event_log_table.dtypes

eventID                             float64
case Spend area text                 object
case Document Type                   object
case Sub spend area text             object
case Purch. Doc. Category name       object
case Vendor                          object
case Item Type                       object
case Item Category                   object
case Spend classification text       object
case Source                          object
case Name                            object
case GR-Based Inv. Verif.             int64
case Item                             int64
case concept:name                    object
case Goods Receipt                   object
event User                           object
event org:resource                   object
event concept:name                   object
event Cumulative net worth (EUR)    float64
event time:timestamp                 object
caseID                               object
dtype: object

In [9]:
#This step is optional to minimize the work needed in harmonization

#Translate object data types of timestamp data into a datetime64[ns] data type for the timestamp. This is a unique datatype from pandas.
timestamp_objects = event_log_table['event time:timestamp'] #declare timestamp to a variable
event_log_table['event time:timestamp']=pd.to_datetime(timestamp_objects)

#Review changes made
#event_log_table['event time:timestamp'].dtypes
event_log_table.dtypes

eventID                                    float64
case Spend area text                        object
case Document Type                          object
case Sub spend area text                    object
case Purch. Doc. Category name              object
case Vendor                                 object
case Item Type                              object
case Item Category                          object
case Spend classification text              object
case Source                                 object
case Name                                   object
case GR-Based Inv. Verif.                    int64
case Item                                    int64
case concept:name                           object
case Goods Receipt                          object
event User                                  object
event org:resource                          object
event concept:name                          object
event Cumulative net worth (EUR)           float64
event time:timestamp                datetime64[ns]
caseID                                      object
dtype: object

In [10]:
#This step is optional to minimize the work needed in harmonization 

#Translate object data types of object data types (which contains different possible formats) to a clear string data type format
#for loops where used as they enable somewhat automated transformations 
# = for assigning values
# == operator is used to test equality
for log_column in log_columns:
    if event_log_table[log_column].dtype == 'object': #check if the column has an object data type
        event_log_table[log_column] = event_log_table[log_column].astype('string') #change it to a string

#Review changes
#event_log_table['timestamp'].dtypes
event_log_table.dtypes

eventID                                    float64
case Spend area text                        string
case Document Type                          string
case Sub spend area text                    string
case Purch. Doc. Category name              string
case Vendor                                 string
case Item Type                              string
case Item Category                          string
case Spend classification text              string
case Source                                 string
case Name                                   string
case GR-Based Inv. Verif.                    int64
case Item                                    int64
case concept:name                           string
case Goods Receipt                          string
event User                                  string
event org:resource                          string
event concept:name                          string
event Cumulative net worth (EUR)           float64
event time:timestamp                datetime64[ns]
caseID                                      string
dtype: object

In [11]:
# Reorder the columns of the event log table.
# Checking the log columns list contains each item on the mandatory columns list with the assert statement raises an 'AssertionError' if any of the elements are missing. 
# With the delete method and the == operator, the items are removed in the mandatory columns list from the log columns list.
# Then  using the + operator to combine the mandatory columns list and the log columns list (which has been turned into a list using the tolist method). By doing so, a fresh list of columns in # the desired order is created. Using the [] operator to select only the columns in the newly created list, subsetting the event log table DataFrame. By doing this, the columns in the new #DataFrame are created in the desired order.

for mandatory_column in mandatory_columns:
  assert mandatory_column in log_columns 
  log_columns = log_columns.delete(log_columns == mandatory_column)
log_columns = mandatory_columns + log_columns.tolist()

event_log_table = event_log_table[log_columns]
event_log_table #the for loop above resultes in a move of the mandatory columns to the left side (changes order)

,caseID,event time:timestamp,event concept:name,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
0,4507016139 1,2018-03-14 03:11:00,Record Service Entry Sheet,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,<NA>,<NA>,72.0
1,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,30957.0
2,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,1157.0
3,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,2386.0
4,4507016139 1,2018-03-14 03:11:00,Record Service Entry Sheet,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,<NA>,<NA>,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349521,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349522,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349523,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349524,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349525,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0

Here we are going to reset the index and reorder the event log with a new index

Setting the inplace parameter to True and using the reset index method to reset the DataFrame's index. 
This adds a new column to the DataFrame containing the old index values and resets the index to a range of sequential integers beginning at 0. 
Using the rename method and the inplace parameter set to True, rename the column containing the previous index values. 
A dictionary that maps the old column name "index" to the new column name "EventIndex" makes up the columns parameter.
Using the set index method and the inplace parameter set to True, the DataFrame's index is changed to the 'EventIndex' column. 
This will remove the "EventIndex" column from the data and make it the new index of the DataFrame.

In [12]:
# Number every single event in the event log.
# Every single event is represented by a line in the event log file.
event_log_table.reset_index(inplace=True)
event_log_table.rename(columns={'index': 'EventIndex'}, inplace=True)
event_log_table.set_index('EventIndex', inplace=True)

#review changes
event_log_table

/var/folders/vz/snd73j8d2mj817493bt9ykfc0000gn/T/ipykernel_63845/2322881527.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_log_table.rename(columns={'index': 'EventIndex'}, inplace=True)

,caseID,event time:timestamp,event concept:name,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
EventIndex,,,,,,,,,,,,,,,,,,,,,
0,4507016139 1,2018-03-14 03:11:00,Record Service Entry Sheet,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,<NA>,<NA>,72.0
1,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,30957.0
2,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,1157.0
3,4507016139 1,2018-03-14 03:11:00,Record Goods Receipt,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,batch_07,batch_07,2386.0
4,4507016139 1,2018-03-14 03:11:00,Record Service Entry Sheet,2.270000e+14,Logistics,Standard PO,Road Packed,Purchase order,vendorID_0472,Service,...,NPR,sourceSystemID_0000,vendor_0457,1,1,4507016139_00001,True,<NA>,<NA>,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349521,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349522,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349523,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349524,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0
349525,4507032138 1,2018-05-29 00:53:00,Record Service Entry Sheet,4.690000e+14,Logistics,Standard PO,Other Logistics Services,Purchase order,vendorID_0230,Service,...,NPR,sourceSystemID_0000,vendor_0225,1,1,4507032138_00001,True,<NA>,<NA>,13.0

In [13]:
#defining a new dictionary  overview_columns with log columns as the elements
content_overview_columns = [(log_column, ['Supplier2_Comparative_Mining']) for log_column in log_columns]
extra_overview_columns = [('Event log column property', ['Supplier2_Comparative_Mining'])]
overview_columns = dict(extra_overview_columns + content_overview_columns)
overview_table = pd.DataFrame(overview_columns)

# To add a vertically indented name to the index in the console output.
overview_table.set_index('Event log column property', inplace=True)
overview_columns

{'Event log column property': ['Supplier2_Comparative_Mining'],
 'caseID': ['Supplier2_Comparative_Mining'],
 'event time:timestamp': ['Supplier2_Comparative_Mining'],
 'event concept:name': ['Supplier2_Comparative_Mining'],
 'eventID ': ['Supplier2_Comparative_Mining'],
 'case Spend area text': ['Supplier2_Comparative_Mining'],
 'case Document Type': ['Supplier2_Comparative_Mining'],
 'case Sub spend area text': ['Supplier2_Comparative_Mining'],
 'case Purch. Doc. Category name': ['Supplier2_Comparative_Mining'],
 'case Vendor': ['Supplier2_Comparative_Mining'],
 'case Item Type': ['Supplier2_Comparative_Mining'],
 'case Item Category': ['Supplier2_Comparative_Mining'],
 'case Spend classification text': ['Supplier2_Comparative_Mining'],
 'case Source': ['Supplier2_Comparative_Mining'],
 'case Name': ['Supplier2_Comparative_Mining'],
 'case GR-Based Inv. Verif.': ['Supplier2_Comparative_Mining'],
 'case Item': ['Supplier2_Comparative_Mining'],
 'case concept:name': ['Supplier2_Comparative_Mining'],
 'case Goods Receipt': ['Supplier2_Comparative_Mining'],
 'event User': ['Supplier2_Comparative_Mining'],
 'event org:resource': ['Supplier2_Comparative_Mining'],
 'event Cumulative net worth (EUR)': ['Supplier2_Comparative_Mining']}

In [14]:
#view the new overview_table to construct the Meta-DataFrame
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
Event log column property,,,,,,,,,,,,,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,...,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining

<h2>Multiple variables based on event data proprocessing which are used for the Meta-DataFrame</h2>

The author uses the pandas .loc function which is an indexer in Pandas is used to choose rows and columns from a DataFrame based on labels.

The snippet below is called title property X as it will be added to the overview table (Meta-DataFrame) with the log columns list's elements as keys and the log column itself as a value, if the title associated with the log column is present in the titles dictionary (if it does not exist in the titles dictionary). 

Then, a new row with the label "Title" and the values from the title property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 

When this code block is run, a new row with the label "Title" and values representing the names of each log column will appear in the overview table DataFrame (or the log column itself if no title is provided).

In [15]:
# Overview for property: Titles - For the Meta-DataFrame
# Depending on whether the title for the log column is present in the titles dictionary, the values of the log columns list are either the log column itself or its associated title (if it does not exist in the titles dictionary).
title_property = {}

for log_column in log_columns:
    if log_column in titles:
        title = titles[log_column]
    else:
        title = log_column
    title_property[log_column] = title


Then, a new row with the label "Title" and the values from the title property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 
When this code block is run, a new row with the label "Title" and values representing the names of each log column will appear in the overview table DataFrame (or the log column itself if no title is provided).

In [16]:
overview_table.loc['Title'] = title_property
overview_table.loc['Title']

caseID                                                       Case ID
event time:timestamp                                       Timestamp
event concept:name                                          Activity
eventID                                                     eventID
case Spend area text                            case Spend area text
case Document Type                                case Document Type
case Sub spend area text                    case Sub spend area text
case Purch. Doc. Category name        case Purch. Doc. Category name
case Vendor                                              case Vendor
case Item Type                                        case Item Type
case Item Category                                case Item Category
case Spend classification text        case Spend classification text
case Source                                              case Source
case Name                                                  case Name
case GR-Based Inv. Verif.                  case GR-Based Inv. Verif.
case Item                                                  case Item
case concept:name                                  case concept:name
case Goods Receipt                                case Goods Receipt
event User                                                event User
event org:resource                                event org:resource
event Cumulative net worth (EUR)    event Cumulative net worth (EUR)
Name: Title, dtype: object

<h2>Dictionary {for mandatory and additional attributes}</h2>

This code block generates a new dictionary called importance property whose keys are the items in the list of log columns and whose values are either "Mandatory attribute" or "Additional attribute" depending on whether the log column is included in the mandatory columns list or not. 
Then, a new row with the label "Importance" and values taken from the importance property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 
When this code block is run, a new row with the label "Importance" and the values "Mandatory attribute" or "Additional attribute" for each log column, depending on whether that column is in the mandatory columns list or not, will appear in the overview table DataFrame.

The concept is used for other data attributes as well

In [17]:
# Overview property: Label for columns either 'Mandatory attribute' or 'additional_attributes' - For the Meta-DataFrame

importance_property = {}
for log_column in log_columns:
    if log_column in mandatory_columns:
        importance_property[log_column] = 'Mandatory attribute' 
    else:
        importance_property[log_column] = 'Additional attribute'

overview_table.loc['Importance'] = importance_property
overview_table.loc['Importance']

caseID                               Mandatory attribute
event time:timestamp                 Mandatory attribute
event concept:name                   Mandatory attribute
eventID                              Mandatory attribute
case Spend area text                Additional attribute
case Document Type                  Additional attribute
case Sub spend area text            Additional attribute
case Purch. Doc. Category name      Additional attribute
case Vendor                         Additional attribute
case Item Type                      Additional attribute
case Item Category                  Additional attribute
case Spend classification text      Additional attribute
case Source                         Additional attribute
case Name                           Additional attribute
case GR-Based Inv. Verif.           Additional attribute
case Item                           Additional attribute
case concept:name                   Additional attribute
case Goods Receipt                  Additional attribute
event User                          Additional attribute
event org:resource                  Additional attribute
event Cumulative net worth (EUR)    Additional attribute
Name: Importance, dtype: object

The goal of this code snippet is to add a new row to the Meta-Dataframe termed overview table, where the keys are the columns in a list called log columns and the values are strings indicating whether the column is at the "Event level" or the "Case level." The values are determined by examining the column name for the string "event" or "case," respectively.

In [18]:
# Overview property: The level of the event data attribute in the overview table
level_property = {}
for log_column in log_columns:
  if 'event' in log_column:
    level_property[log_column] = 'Event level'
  if 'case' in log_column:
    level_property[log_column] = 'Case level'

overview_table.loc['Level'] = level_property
overview_table.loc['Level']

#NaN's can manually be changed in the Meta-DataFrame

caseID                               Case level
event time:timestamp                Event level
event concept:name                  Event level
eventID                             Event level
case Spend area text                 Case level
case Document Type                   Case level
case Sub spend area text             Case level
case Purch. Doc. Category name       Case level
case Vendor                          Case level
case Item Type                       Case level
case Item Category                   Case level
case Spend classification text       Case level
case Source                          Case level
case Name                            Case level
case GR-Based Inv. Verif.            Case level
case Item                            Case level
case concept:name                    Case level
case Goods Receipt                   Case level
event User                          Event level
event org:resource                  Event level
event Cumulative net worth (EUR)    Event level
Name: Level, dtype: object

In [19]:
# Overview property: Data type
data_type_property = {}
datatypes = event_log_table.dtypes
for log_column in log_columns:
  data_type_property[log_column] = datatypes[log_column]

overview_table.loc['Data type'] = data_type_property

This snippet adds a new row to the Meta-Dataframe in Pandas, with the keys being the columns in a list called log columns and the values being the data types of the corresponding columns in an event log table DataFrame.

In [20]:
# Overview property: Data type
data_type_property = {}
datatypes = event_log_table.dtypes
for log_column in log_columns:
    data_type_property[log_column] = datatypes[log_column]

overview_table.loc['Data type'] = data_type_property
overview_table.loc['Data type']

caseID                                      string
event time:timestamp                datetime64[ns]
event concept:name                          string
eventID                                    float64
case Spend area text                        string
case Document Type                          string
case Sub spend area text                    string
case Purch. Doc. Category name              string
case Vendor                                 string
case Item Type                              string
case Item Category                          string
case Spend classification text              string
case Source                                 string
case Name                                   string
case GR-Based Inv. Verif.                    int64
case Item                                    int64
case concept:name                           string
case Goods Receipt                          string
event User                                  string
event org:resource                          string
event Cumulative net worth (EUR)           float64
Name: Data type, dtype: object

In [21]:
# Overview property: Count the number of entries for the Meta-Dataframe
number_of_entries_property = {}
for log_column in log_columns:
    number_of_entries_property[log_column] = len(event_log_table)

overview_table.loc['Number of entries'] = number_of_entries_property
overview_table.loc['Number of entries']

caseID                              349526
event time:timestamp                349526
event concept:name                  349526
eventID                             349526
case Spend area text                349526
case Document Type                  349526
case Sub spend area text            349526
case Purch. Doc. Category name      349526
case Vendor                         349526
case Item Type                      349526
case Item Category                  349526
case Spend classification text      349526
case Source                         349526
case Name                           349526
case GR-Based Inv. Verif.           349526
case Item                           349526
case concept:name                   349526
case Goods Receipt                  349526
event User                          349526
event org:resource                  349526
event Cumulative net worth (EUR)    349526
Name: Number of entries, dtype: object

In [22]:
# Overview property: Number of unique entries
number_of_unique_entries_property = {}
for log_column in log_columns:
  count = event_log_table[log_column].value_counts().count()
  number_of_unique_entries_property[log_column] = count

overview_table.loc['Number of unique entries'] = number_of_unique_entries_property
overview_table.loc['Number of unique entries']

caseID                              56127
event time:timestamp                42173
event concept:name                     28
eventID                               243
case Spend area text                   18
case Document Type                      2
case Sub spend area text              109
case Purch. Doc. Category name          1
case Vendor                          1109
case Item Type                          5
case Item Category                      3
case Spend classification text          4
case Source                             1
case Name                            1050
case GR-Based Inv. Verif.               2
case Item                             233
case concept:name                   53733
case Goods Receipt                      1
event User                            333
event org:resource                    333
event Cumulative net worth (EUR)    11330
Name: Number of unique entries, dtype: object

In [23]:
#Overview property: List of up to 100 unique entries (to grasp an understanding of how the data looks and it is structured and not just metrics)
unique_entries_property = {}
for log_column in log_columns:
    unique_entries = event_log_table[log_column].unique()
    unique_entries = list(unique_entries)
    unique_entries = unique_entries[:100]
    unique_entries_property[log_column] = unique_entries

overview_table.loc['List up to 100 unique entries to view the structure of the event attributes']= unique_entries_property
unique_entries_property

{'caseID': ['4507016139 1',
  '4507016140 10',
  '4507016140 20',
  '4507016140 30',
  '4507016141 10',
  '4507016141 100',
  '4507016141 20',
  '4507016141 30',
  '4507016141 40',
  '4507016141 50',
  '4507016141 60',
  '4507016141 70',
  '4507016141 80',
  '4507016141 90',
  '4507016142 10',
  '4507016143 10',
  '4507016143 20',
  '4507016143 30',
  '4507016143 40',
  '4507016144 10',
  '4507016144 20',
  '4507016144 30',
  '4507016145 10',
  '4507016145 20',
  '4507016145 30',
  '4507016145 40',
  '4507016145 50',
  '4507016146 10',
  '4507016146 100',
  '4507016146 110',
  '4507016146 120',
  '4507016146 130',
  '4507016146 140',
  '4507016146 20',
  '4507016146 30',
  '4507016146 40',
  '4507016146 50',
  '4507016146 60',
  '4507016146 70',
  '4507016146 80',
  '4507016146 90',
  '4507016147 10',
  '4507016147 20',
  '4507016148 10',
  '4507016149 10',
  '4507016149 100',
  '4507016149 110',
  '4507016149 120',
  '4507016149 130',
  '4507016149 140',
  '4507016149 150',
  '4507016149 160',
  '4507016149 20',
  '4507016149 30',
  '4507016149 40',
  '4507016149 50',
  '4507016149 60',
  '4507016149 70',
  '4507016149 80',
  '4507016149 90',
  '4507016150 10',
  '4507016150 20',
  '4507016150 30',
  '4507016150 40',
  '4507016150 50',
  '4507016150 60',
  '4507016150 70',
  '4507016151 10',
  '4507016151 100',
  '4507016151 20',
  '4507016151 30',
  '4507016151 40',
  '4507016151 50',
  '4507016151 60',
  '4507016151 70',
  '4507016151 80',
  '4507016151 90',
  '4507016152 10',
  '4507016152 100',
  '4507016152 110',
  '4507016152 120',
  '4507016152 130',
  '4507016152 140',
  '4507016152 150',
  '4507016152 160',
  '4507016152 20',
  '4507016152 30',
  '4507016152 40',
  '4507016152 50',
  '4507016152 60',
  '4507016152 70',
  '4507016152 80',
  '4507016152 90',
  '4507016153 10',
  '4507016154 10',
  '4507016154 20',
  '4507016155 10',
  '4507016155 100',
  '4507016155 110',
  '4507016155 120'],
 'event time:timestamp': [numpy.datetime64('2018-03-14T03:11:00.000000000'),
  numpy.datetime64('2018-03-14T03:13:00.000000000'),
  numpy.datetime64('2018-03-14T03:14:00.000000000'),
  numpy.datetime64('2018-03-14T03:15:00.000000000'),
  numpy.datetime64('2018-03-14T03:16:00.000000000'),
  numpy.datetime64('2018-03-14T03:17:00.000000000'),
  numpy.datetime64('2018-03-14T05:33:00.000000000'),
  numpy.datetime64('2018-03-14T09:03:00.000000000'),
  numpy.datetime64('2018-03-16T08:35:00.000000000'),
  numpy.datetime64('2018-03-20T00:59:00.000000000'),
  numpy.datetime64('2018-03-20T10:13:00.000000000'),
  numpy.datetime64('2018-04-26T13:14:00.000000000'),
  numpy.datetime64('2018-03-20T07:05:00.000000000'),
  numpy.datetime64('NaT'),
  numpy.datetime64('2018-03-28T01:59:00.000000000'),
  numpy.datetime64('2018-04-03T14:30:00.000000000'),
  numpy.datetime64('2018-04-23T11:34:00.000000000'),
  numpy.datetime64('2018-05-09T09:17:00.000000000'),
  numpy.datetime64('2018-05-24T15:33:00.000000000'),
  numpy.datetime64('2018-03-16T12:14:00.000000000'),
  numpy.datetime64('2018-03-16T18:17:00.000000000'),
  numpy.datetime64('2018-04-06T01:59:00.000000000'),
  numpy.datetime64('2018-04-10T16:33:00.000000000'),
  numpy.datetime64('2018-04-11T12:58:00.000000000'),
  numpy.datetime64('2018-06-07T15:11:00.000000000'),
  numpy.datetime64('2018-03-16T12:16:00.000000000'),
  numpy.datetime64('2018-03-22T11:59:00.000000000'),
  numpy.datetime64('2018-04-07T01:59:00.000000000'),
  numpy.datetime64('2018-04-09T12:13:00.000000000'),
  numpy.datetime64('2018-04-10T14:29:00.000000000'),
  numpy.datetime64('2018-06-07T15:12:00.000000000'),
  numpy.datetime64('2018-03-16T15:41:00.000000000'),
  numpy.datetime64('2018-03-16T12:21:00.000000000'),
  numpy.datetime64('2018-04-05T17:38:00.000000000'),
  numpy.datetime64('2018-03-27T15:36:00.000000000'),
  numpy.datetime64('2018-03-30T13:42:00.000000000'),
  numpy.datetime64('2018-03-27T15:34:00.000000000'),
  numpy.datetime64('2018-03-23T13:16:00.000000000'),
  numpy.datetime64('2018-03-28T19:55:00.000000000'),
  numpy.datetime64('2018-03-21T00:59:00.000000000'),
  numpy.datetime64('2018-03-21T13:36:00.000000000'),
  numpy.datetime64('2018-04-04T19:06:00.000000000'),
  numpy.datetime64('2018-04-26T13:12:00.000000000'),
  numpy.datetime64('2018-03-22T08:19:00.000000000'),
  numpy.datetime64('2018-03-16T12:22:00.000000000'),
  numpy.datetime64('2018-04-01T01:59:00.000000000'),
  numpy.datetime64('2018-04-03T13:53:00.000000000'),
  numpy.datetime64('2018-04-05T09:03:00.000000000'),
  numpy.datetime64('2018-05-09T16:09:00.000000000'),
  numpy.datetime64('2018-03-16T12:36:00.000000000'),
  numpy.datetime64('2018-03-16T13:53:00.000000000'),
  numpy.datetime64('2018-04-05T10:15:00.000000000'),
  numpy.datetime64('2018-04-10T01:59:00.000000000'),
  numpy.datetime64('2018-04-10T17:19:00.000000000'),
  numpy.datetime64('2018-03-16T12:24:00.000000000'),
  numpy.datetime64('2018-03-17T00:59:00.000000000'),
  numpy.datetime64('2018-03-19T14:53:00.000000000'),
  numpy.datetime64('2018-03-22T11:44:00.000000000'),
  numpy.datetime64('2018-04-26T13:13:00.000000000'),
  numpy.datetime64('2018-03-16T12:25:00.000000000'),
  numpy.datetime64('2018-04-05T10:16:00.000000000'),
  numpy.datetime64('2018-04-10T17:22:00.000000000'),
  numpy.datetime64('2018-04-11T19:52:00.000000000'),
  numpy.datetime64('2018-03-16T12:26:00.000000000'),
  numpy.datetime64('2018-04-18T15:18:00.000000000'),
  numpy.datetime64('2018-04-19T01:59:00.000000000'),
  numpy.datetime64('2018-06-04T19:43:00.000000000'),
  numpy.datetime64('2018-06-28T16:05:00.000000000'),
  numpy.datetime64('2018-03-16T12:31:00.000000000'),
  numpy.datetime64('2018-03-24T00:59:00.000000000'),
  numpy.datetime64('2018-03-26T15:26:00.000000000'),
  numpy.datetime64('2018-03-29T13:29:00.000000000'),
  numpy.datetime64('2018-04-12T16:07:00.000000000'),
  numpy.datetime64('2018-03-26T15:28:00.000000000'),
  numpy.datetime64('2018-03-16T12:33:00.000000000'),
  numpy.datetime64('2018-04-09T15:41:00.000000000'),
  numpy.datetime64('2018-04-10T17:25:00.000000000'),
  numpy.datetime64('2018-04-11T12:40:00.000000000'),
  numpy.datetime64('2018-04-12T09:32:00.000000000'),
  numpy.datetime64('2018-04-12T18:21:00.000000000'),
  numpy.datetime64('2018-05-24T15:35:00.000000000'),
  numpy.datetime64('2018-03-16T12:34:00.000000000'),
  numpy.datetime64('2018-04-03T15:44:00.000000000'),
  numpy.datetime64('2018-04-12T09:30:00.000000000'),
  numpy.datetime64('2018-03-16T12:37:00.000000000'),
  numpy.datetime64('2018-04-20T01:59:00.000000000'),
  numpy.datetime64('2018-04-23T18:51:00.000000000'),
  numpy.datetime64('2018-04-27T10:21:00.000000000'),
  numpy.datetime64('2018-04-28T04:14:00.000000000'),
  numpy.datetime64('2018-06-28T16:02:00.000000000'),
  numpy.datetime64('2018-03-16T12:39:00.000000000'),
  numpy.datetime64('2018-03-19T15:35:00.000000000'),
  numpy.datetime64('2018-03-21T12:34:00.000000000'),
  numpy.datetime64('2018-03-20T15:59:00.000000000'),
  numpy.datetime64('2018-03-28T12:30:00.000000000'),
  numpy.datetime64('2018-03-20T15:48:00.000000000'),
  numpy.datetime64('2018-03-20T16:02:00.000000000'),
  numpy.datetime64('2018-03-16T12:43:00.000000000'),
  numpy.datetime64('2018-03-21T07:47:00.000000000'),
  numpy.datetime64('2018-04-06T17:34:00.000000000')],
 'event concept:name': ['Record Service Entry Sheet',
  'Record Goods Receipt',
  'Create Purchase Order Item',
  'Receive Order Confirmation',
  'Vendor creates invoice',
  'Record Invoice Receipt',
  'Clear Invoice',
  <NA>,
  'Remove Payment Block',
  'Change Quantity',
  'Price Change',
  'Delete Purchase Order Item',
  'Vendor creates debit memo',
  'Revoke Invoice Receipt',
  'Change Delivery Indicator',
  'Block Purchase Order Item',
  'Reactivate Purchase Order Item',
  'Change Storage Location',
  'Revoke Goods Receipt',
  'Create Purchase Requisition Item',
  'Update Order Confirmation',
  'Change Approval for Purchase Order',
  'Revoke Subsequent Invoice',
  'Record Subsequent Invoice',
  'Change payment term',
  'Change Currency',
  'Release Purchase Order',
  'Set Payment Block',
  'Change Rejection Indicator'],
 'eventID ': [227000000000000.0,
  nan,
  228000000000000.0,
  229000000000000.0,
  230000000000000.0,
  231000000000000.0,
  232000000000000.0,
  233000000000000.0,
  234000000000000.0,
  235000000000000.0,
  236000000000000.0,
  237000000000000.0,
  238000000000000.0,
  239000000000000.0,
  240000000000000.0,
  241000000000000.0,
  242000000000000.0,
  243000000000000.0,
  244000000000000.0,
  245000000000000.0,
  246000000000000.0,
  247000000000000.0,
  248000000000000.0,
  249000000000000.0,
  250000000000000.0,
  251000000000000.0,
  252000000000000.0,
  253000000000000.0,
  254000000000000.0,
  255000000000000.0,
  256000000000000.0,
  257000000000000.0,
  258000000000000.0,
  259000000000000.0,
  260000000000000.0,
  261000000000000.0,
  262000000000000.0,
  263000000000000.0,
  264000000000000.0,
  265000000000000.0,
  266000000000000.0,
  267000000000000.0,
  268000000000000.0,
  269000000000000.0,
  270000000000000.0,
  271000000000000.0,
  272000000000000.0,
  273000000000000.0,
  274000000000000.0,
  275000000000000.0,
  276000000000000.0,
  277000000000000.0,
  278000000000000.0,
  279000000000000.0,
  280000000000000.0,
  281000000000000.0,
  282000000000000.0,
  283000000000000.0,
  284000000000000.0,
  285000000000000.0,
  286000000000000.0,
  287000000000000.0,
  288000000000000.0,
  289000000000000.0,
  290000000000000.0,
  291000000000000.0,
  292000000000000.0,
  293000000000000.0,
  294000000000000.0,
  295000000000000.0,
  296000000000000.0,
  297000000000000.0,
  298000000000000.0,
  299000000000000.0,
  300000000000000.0,
  301000000000000.0,
  302000000000000.0,
  303000000000000.0,
  304000000000000.0,
  305000000000000.0,
  306000000000000.0,
  307000000000000.0,
  308000000000000.0,
  309000000000000.0,
  310000000000000.0,
  311000000000000.0,
  312000000000000.0,
  313000000000000.0,
  314000000000000.0,
  315000000000000.0,
  316000000000000.0,
  317000000000000.0,
  318000000000000.0,
  319000000000000.0,
  320000000000000.0,
  321000000000000.0,
  322000000000000.0,
  323000000000000.0,
  324000000000000.0,
  325000000000000.0],
 'case Spend area text': ['Logistics',
  'Packaging',
  'Sales',
  'CAPEX & SOCS',
  'Latex & Monomers',
  'Marketing',
  'Trading & End Products',
  'Specialty Resins',
  'Others',
  'Additives',
  'Titanium Dioxides',
  'Pigments & Colorants',
  'Solvents',
  'undefined',
  'Commodity Resins',
  'Workforce Services',
  'Spend Area Unidentified',
  'Enterprise Services',
  <NA>],
 'case Document Type': ['Standard PO', 'Framework order', <NA>],
 'case Sub spend area text': ['Road Packed',
  'Metal Containers & Lids < 30L',
  'Labels',
  'Plastic Containers & Lids < 30L',
  'Products for Resale',
  'MRO (components)',
  'Vinyl Acetate Ethylenes',
  'Commercial Printing',
  'Trading products (old structure)',
  'Isocyanates',
  'Pure Acrylics',
  'Polyamides & Polyamines',
  'Alkyd Resins',
  'Polyurethane Resins',
  'Customers',
  'Styrene Acrylics',
  'Defoamers & Antifoams',
  'Packaging - Other',
  'Biocides',
  'Rheology & Thixotropic Agents',
  'Extenders',
  'Latexes - Other',
  'Chloride',
  'Surfactants',
  'Colorants',
  'Public Relations',
  'Glycol & Ether Solvents',
  'undefined',
  'Carbon Black Pigments',
  'Opaque Polymers',
  'Driers & Antiskinning Agents',
  'Drums',
  'Paperboard',
  'Light & Heat Stabilizers',
  'Waxes',
  'Corrosion Inhibitors',
  'Raw Material',
  'Laboratory Supplies & Services',
  'Catalysts & Initiators',
  'Color Collateral',
  'Commodity Resins Precursors',
  'Ester Solvents',
  'Vinyl Acrylics',
  'Packaging',
  'Aliphatic Solvents',
  'Other Logistics Services',
  'Sea',
  'Mixing Machines',
  'Exhibitions & seminars',
  'Polyvinyl Acetates',
  'Facility Management',
  'Technical Services',
  'Sulphate',
  'Neutralisation Agents',
  'Closures',
  'Inorganic Pigments',
  'Warehousing',
  'Tubes',
  'Intermediate Bulk Containers (IBC)',
  'Utilities',
  'Pallets',
  'Marketing Support Services',
  'HR Services',
  'Plastic Film',
  'Business Gifts & Promotional Items',
  'Epoxy Resins - Liquid',
  'Gasses',
  'Additives - Other',
  'Point of Sales',
  'Spend Area Unidentified',
  'QHSE Services',
  'ICT Hardware',
  'Jerry Cans',
  'Amino Resins',
  'Bags',
  <NA>,
  'Bottles',
  'Specialty Resins Precursors',
  'UV Resins',
  'Specialty Resins - Other',
  'Ketones Solvents',
  'Hybrid Containers',
  'Process Automation & Instrumentation',
  'Fire Protection Agents',
  'Effect Pigments',
  'Acrylic Resins ¬ñ Liquid',
  'Organic Pigments',
  'Design',
  'Adhesion Promotors',
  'Alcohol Solvents',
  'Sales Promotion',
  'Plasticizers',
  'Transport & Hoisting Equipment',
  'Solvents - Other',
  'Equipment',
  'Aromatic Solvents',
  'Epoxy Resins - Solid',
  'Polyester Resins - Liquid',
  'Caseins & Starches',
  'Spectrophotometers'],
 'case Purch. Doc. Category name': ['Purchase order', <NA>],
 'case Vendor': ['vendorID_0472',
  'vendorID_0106',
  'vendorID_0103',
  'vendorID_0104',
  'vendorID_0105',
  'vendorID_0284',
  'vendorID_0115',
  'vendorID_0114',
  'vendorID_0755',
  'vendorID_0236',
  'vendorID_0237',
  'vendorID_0756',
  'vendorID_0121',
  'vendorID_0239',
  'vendorID_1135',
  'vendorID_0671',
  'vendorID_0716',
  'vendorID_0672',
  'vendorID_1120',
  'vendorID_0271',
  'vendorID_0120',
  'vendorID_0468',
  'vendorID_0245',
  'vendorID_0246',
  'vendorID_0302',
  'vendorID_0937',
  'vendorID_0381',
  'vendorID_0110',
  'vendorID_0138',
  'vendorID_0251',
  'vendorID_0145',
  'vendorID_0489',
  'vendorID_0135',
  'vendorID_0167',
  'vendorID_0224',
  'vendorID_0264',
  'vendorID_0879',
  'vendorID_0280',
  'vendorID_0433',
  'vendorID_0127',
  'vendorID_0244',
  'vendorID_0243',
  'vendorID_0300',
  'vendorID_0113',
  'vendorID_0283',
  'vendorID_0133',
  'vendorID_0242',
  'vendorID_0130',
  'vendorID_0442',
  'vendorID_0844',
  'vendorID_0448',
  'vendorID_0107',
  'vendorID_0372',
  'vendorID_0152',
  'vendorID_0963',
  'vendorID_0060',
  'vendorID_0136',
  'vendorID_0126',
  'vendorID_0608',
  'vendorID_0220',
  'vendorID_0184',
  'vendorID_1142',
  'vendorID_0144',
  'vendorID_0146',
  'vendorID_0143',
  'vendorID_0917',
  'vendorID_0139',
  'vendorID_0287',
  'vendorID_0524',
  'vendorID_0730',
  'vendorID_0417',
  'vendorID_0422',
  'vendorID_0192',
  'vendorID_0277',
  'vendorID_0457',
  'vendorID_0299',
  'vendorID_0166',
  'vendorID_1328',
  'vendorID_0278',
  'vendorID_0303',
  'vendorID_0506',
  'vendorID_1329',
  'vendorID_0197',
  'vendorID_0444',
  'vendorID_0620',
  'vendorID_0151',
  'vendorID_0615',
  'vendorID_0932',
  'vendorID_0321',
  'vendorID_0579',
  'vendorID_0323',
  'vendorID_0168',
  'vendorID_0583',
  'vendorID_0312',
  'vendorID_1106',
  'vendorID_0128',
  'vendorID_0804',
  'vendorID_0117',
  'vendorID_0326',
  'vendorID_0618'],
 'case Item Type': ['Service',
  'Standard',
  'Third-party',
  'Subcontracting',
  'Consignment',
  <NA>],
 'case Item Category': ['Three way match, invoice after GR',
  'Three way match, invoice before GR',
  <NA>,
  'Consignment'],
 'case Spend classification text': ['NPR', 'PR', 'OTHER', 'undefined', <NA>],
 'case Source': ['sourceSystemID_0000', <NA>],
 'case Name': ['vendor_0457',
  'vendor_0106',
  'vendor_0103',
  'vendor_0104',
  'vendor_0105',
  'vendor_0276',
  'vendor_0115',
  'vendor_0114',
  'vendor_0720',
  'vendor_0231',
  'vendor_0232',
  'vendor_0721',
  'vendor_0120',
  'vendor_0234',
  'vendor_1079',
  'vendor_0646',
  'vendor_0685',
  'vendor_0647',
  'vendor_1065',
  'vendor_0188',
  'vendor_0119',
  'vendor_0453',
  'vendor_0240',
  'vendor_0241',
  'vendor_0293',
  'vendor_0894',
  'vendor_0370',
  'vendor_0110',
  'vendor_0137',
  'vendor_0062',
  'vendor_0144',
  'vendor_0473',
  'vendor_0134',
  'vendor_0165',
  'vendor_0219',
  'vendor_0257',
  'vendor_0839',
  'vendor_0272',
  'vendor_0421',
  'vendor_0126',
  'vendor_0239',
  'vendor_0238',
  'vendor_0291',
  'vendor_0113',
  'vendor_0275',
  'vendor_0132',
  'vendor_0237',
  'vendor_0129',
  'vendor_0429',
  'vendor_0804',
  'vendor_0435',
  'vendor_0107',
  'vendor_0361',
  'vendor_0150',
  'vendor_0920',
  'vendor_0060',
  'vendor_0135',
  'vendor_0125',
  'vendor_0271',
  'vendor_0216',
  'vendor_0164',
  'vendor_1086',
  'vendor_0143',
  'vendor_0142',
  'vendor_0876',
  'vendor_0138',
  'vendor_0278',
  'vendor_0508',
  'vendor_0475',
  'vendor_0406',
  'vendor_0410',
  'vendor_0189',
  'vendor_0269',
  'vendor_0443',
  'vendor_0290',
  'vendor_1269',
  'vendor_0270',
  'vendor_0294',
  'vendor_0490',
  'vendor_1270',
  'vendor_0194',
  'vendor_0431',
  'vendor_0597',
  'vendor_0149',
  'vendor_0594',
  'vendor_0889',
  'vendor_0312',
  'vendor_0305',
  'vendor_0314',
  'vendor_0166',
  'vendor_0565',
  'vendor_0303',
  'vendor_1052',
  'vendor_0127',
  'vendor_0764',
  'vendor_0116',
  'vendor_0317',
  'vendor_0596',
  'vendor_0722',
  'vendor_0036'],
 'case GR-Based Inv. Verif.': [1, 0],
 'case Item': [1,
  10,
  20,
  30,
  100,
  40,
  50,
  60,
  70,
  80,
  90,
  110,
  120,
  130,
  140,
  150,
  160,
  170,
  180,
  190,
  200,
  210,
  220,
  230,
  240,
  250,
  260,
  270,
  280,
  290,
  300,
  310,
  320,
  330,
  340,
  350,
  360,
  370,
  380,
  390,
  400,
  410,
  420,
  430,
  440,
  450,
  460,
  470,
  1000,
  1010,
  1020,
  1030,
  1040,
  1050,
  1060,
  1070,
  1080,
  1090,
  1100,
  480,
  490,
  500,
  510,
  520,
  530,
  540,
  550,
  560,
  570,
  580,
  590,
  600,
  610,
  620,
  630,
  640,
  650,
  660,
  670,
  680,
  690,
  700,
  710,
  720,
  730,
  740,
  750,
  760,
  770,
  780,
  790,
  800,
  810,
  820,
  830,
  840,
  850,
  860,
  870,
  880],
 'case concept:name': ['4507016139_00001',
  '4507016140_00010',
  '4507016140_00020',
  '4507016140_00030',
  <NA>,
  '4507016900_00050',
  '4507016901_00010',
  '4507016902_00010',
  '4507016902_00020',
  '4507016902_00030',
  '4507016902_00040',
  '4507016902_00050',
  '4507016903_00010',
  '4507016903_00100',
  '4507016903_00110',
  '4507016903_00120',
  '4507016903_00130',
  '4507016903_00020',
  '4507016903_00030',
  '4507016903_00040',
  '4507016903_00050',
  '4507016903_00060',
  '4507016903_00070',
  '4507016903_00080',
  '4507016903_00090',
  '4507016904_00010',
  '4507016904_00020',
  '4507016905_00010',
  '4507016905_00020',
  '4507016905_00030',
  '4507016906_00010',
  '4507016907_00010',
  '4507016907_00020',
  '4507016907_00030',
  '4507016908_00010',
  '4507016909_00010',
  '4507016909_00020',
  '4507016910_00010',
  '4507016910_00100',
  '4507016910_00020',
  '4507016910_00030',
  '4507016910_00040',
  '4507016910_00050',
  '4507016910_00060',
  '4507016910_00070',
  '4507016910_00080',
  '4507016910_00090',
  '4507016911_00010',
  '4507016912_00010',
  '4507016912_00020',
  '4507016913_00010',
  '4507016914_00010',
  '4507016915_00010',
  '4507016915_00020',
  '4507016915_00030',
  '4507016916_00010',
  '4507016917_00010',
  '4507016917_00020',
  '4507016917_00030',
  '4507016918_00010',
  '4507016918_00020',
  '4507016918_00030',
  '4507016919_00010',
  '4507016919_00020',
  '4507016920_00010',
  '4507016920_00020',
  '4507016921_00010',
  '4507016921_00020',
  '4507016921_00030',
  '4507016921_00040',
  '4507016921_00050',
  '4507016921_00060',
  '4507016921_00070',
  '4507016922_00010',
  '4507016923_00010',
  '4507016924_00010',
  '4507016925_00010',
  '4507016925_00100',
  '4507016925_00110',
  '4507016925_00120',
  '4507016925_00130',
  '4507016925_00140',
  '4507016925_00020',
  '4507016925_00030',
  '4507016925_00040',
  '4507016925_00050',
  '4507016925_00060',
  '4507016925_00070',
  '4507016925_00080',
  '4507016925_00090',
  '4507016926_00010',
  '4507016926_00100',
  '4507016926_00110',
  '4507016926_00120',
  '4507016926_00130',
  '4507016926_00140',
  '4507016926_00150',
  '4507016926_00160',
  '4507016926_00170',
  '4507016926_00020'],
 'case Goods Receipt': ['True', <NA>],
 'event User': [<NA>,
  'batch_07',
  'batch_03',

In [24]:
# Overview property: Length of the list of up to 100 unique entries
num_displayed_unique_entries_property = {}
for log_column in log_columns:
  unique_entries = event_log_table[log_column].unique()
  unique_entries = list(unique_entries)
  unique_entries = unique_entries[:100]
  num_displayed_unique_entries_property[log_column] = len(unique_entries)

overview_table.loc['Length of the list of up to 100 unique entries'] = num_displayed_unique_entries_property
num_displayed_unique_entries_property

{'caseID': 100,
 'event time:timestamp': 100,
 'event concept:name': 29,
 'eventID ': 100,
 'case Spend area text': 19,
 'case Document Type': 3,
 'case Sub spend area text': 100,
 'case Purch. Doc. Category name': 2,
 'case Vendor': 100,
 'case Item Type': 6,
 'case Item Category': 4,
 'case Spend classification text': 5,
 'case Source': 2,
 'case Name': 100,
 'case GR-Based Inv. Verif.': 2,
 'case Item': 100,
 'case concept:name': 100,
 'case Goods Receipt': 2,
 'event User': 100,
 'event org:resource': 100,
 'event Cumulative net worth (EUR)': 100}

In [25]:
# Inspect the overview table
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
Event log column property,,,,,,,,,,,,,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,...,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining
Title,Case ID,Timestamp,Activity,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
Importance,Mandatory attribute,Mandatory attribute,Mandatory attribute,Mandatory attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,...,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute
Level,Case level,Event level,Event level,Event level,Case level,Case level,Case level,Case level,Case level,Case level,...,Case level,Case level,Case level,Case level,Case level,Case level,Case level,Event level,Event level,Event level
Data type,string,datetime64[ns],string,float64,string,string,string,string,string,string,...,string,string,string,int64,int64,string,string,string,string,float64
Number of entries,349526,349526,349526,349526,349526,349526,349526,349526,349526,349526,...,349526,349526,349526,349526,349526,349526,349526,349526,349526,349526
Number of unique entries,56127,42173,28,243,18,2,109,1,1109,5,...,4,1,1050,2,233,53733,1,333,333,11330
List up to 100 unique entries to view the structure of the event attributes,"[4507016139 1, 4507016140 10, 4507016140 20, 4...","[2018-03-14T03:11:00.000000000, 2018-03-14T03:...","[Record Service Entry Sheet, Record Goods Rece...","[227000000000000.0, nan, 228000000000000.0, 22...","[Logistics, Packaging, Sales, CAPEX & SOCS, La...","[Standard PO, Framework order, <NA>]","[Road Packed, Metal Containers & Lids < 30L, L...","[Purchase order, <NA>]","[vendorID_0472, vendorID_0106, vendorID_0103, ...","[Service, Standard, Third-party, Subcontractin...",...,"[NPR, PR, OTHER, undefined, <NA>]","[sourceSystemID_0000, <NA>]","[vendor_0457, vendor_0106, vendor_0103, vendor...","[1, 0]","[1, 10, 20, 30, 100, 40, 50, 60, 70, 80, 90, 1...","[4507016139_00001, 4507016140_00010, 450701614...","[True, <NA>]","[<NA>, batch_07, batch_03, user_029, user_030,...","[<NA>, batch_07, batch_03, user_029, user_030,...","[72.0, 30957.0, 1157.0, 2386.0, 21699.0, 144.0..."
Length of the list of up to 100 unique entries,100,100,29,100,19,3,100,2,100,6,...,5,2,100,2,100,100,2,100,100,100

In [26]:
# Overview property: Number of duplicate entries
number_of_duplicate_entries_property = {}
for log_column in log_columns:
  number_of_duplicate_entries_property[log_column] = number_of_entries_property[log_column] - number_of_unique_entries_property[log_column]

overview_table.loc['Number of duplicate entries'] = number_of_duplicate_entries_property
overview_table.loc['Number of duplicate entries']

caseID                              293399
event time:timestamp                307353
event concept:name                  349498
eventID                             349283
case Spend area text                349508
case Document Type                  349524
case Sub spend area text            349417
case Purch. Doc. Category name      349525
case Vendor                         348417
case Item Type                      349521
case Item Category                  349523
case Spend classification text      349522
case Source                         349525
case Name                           348476
case GR-Based Inv. Verif.           349524
case Item                           349293
case concept:name                   295793
case Goods Receipt                  349525
event User                          349193
event org:resource                  349193
event Cumulative net worth (EUR)    338196
Name: Number of duplicate entries, dtype: object

In [27]:
# Overview property: Number of undefined entries
number_of_undefined_entries_property = {}
nan_info = event_log_table.isna().sum()
for log_column in log_columns:
    number_of_undefined_entries_property[log_column] = nan_info[log_column]

overview_table.loc['Number of undefined entries'] = number_of_undefined_entries_property
number_of_undefined_entries_property

{'caseID': 1495,
 'event time:timestamp': 16078,
 'event concept:name': 16078,
 'eventID ': 133,
 'case Spend area text': 11,
 'case Document Type': 11,
 'case Sub spend area text': 11,
 'case Purch. Doc. Category name': 438,
 'case Vendor': 11,
 'case Item Type': 11,
 'case Item Category': 784,
 'case Spend classification text': 11,
 'case Source': 11,
 'case Name': 11,
 'case GR-Based Inv. Verif.': 0,
 'case Item': 0,
 'case concept:name': 16078,
 'case Goods Receipt': 16078,
 'event User': 103390,
 'event org:resource': 103390,
 'event Cumulative net worth (EUR)': 16078}

In [28]:
# Overview propperty: Number of undefined entries in percentages
percentage_of_undefined_entries_property = {}
nan_info = event_log_table.isna().sum()
for log_column in log_columns:
    percentage = nan_info[log_column]/len(event_log_table)*100 #len calculates the length of a variable
    percentage = f'{percentage:.2f}'
    percentage_of_undefined_entries_property[log_column] = percentage

overview_table.loc['Percentage of undefined entries'] = percentage_of_undefined_entries_property
percentage_of_undefined_entries_property

{'caseID': '0.43',
 'event time:timestamp': '4.60',
 'event concept:name': '4.60',
 'eventID ': '0.04',
 'case Spend area text': '0.00',
 'case Document Type': '0.00',
 'case Sub spend area text': '0.00',
 'case Purch. Doc. Category name': '0.13',
 'case Vendor': '0.00',
 'case Item Type': '0.00',
 'case Item Category': '0.22',
 'case Spend classification text': '0.00',
 'case Source': '0.00',
 'case Name': '0.00',
 'case GR-Based Inv. Verif.': '0.00',
 'case Item': '0.00',
 'case concept:name': '4.60',
 'case Goods Receipt': '4.60',
 'event User': '29.58',
 'event org:resource': '29.58',
 'event Cumulative net worth (EUR)': '4.60'}

In [29]:
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
Event log column property,,,,,,,,,,,,,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,...,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining
Title,Case ID,Timestamp,Activity,eventID,case Spend area text,case Document Type,case Sub spend area text,case Purch. Doc. Category name,case Vendor,case Item Type,...,case Spend classification text,case Source,case Name,case GR-Based Inv. Verif.,case Item,case concept:name,case Goods Receipt,event User,event org:resource,event Cumulative net worth (EUR)
Importance,Mandatory attribute,Mandatory attribute,Mandatory attribute,Mandatory attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,...,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute
Level,Case level,Event level,Event level,Event level,Case level,Case level,Case level,Case level,Case level,Case level,...,Case level,Case level,Case level,Case level,Case level,Case level,Case level,Event level,Event level,Event level
Data type,string,datetime64[ns],string,float64,string,string,string,string,string,string,...,string,string,string,int64,int64,string,string,string,string,float64
Number of entries,349526,349526,349526,349526,349526,349526,349526,349526,349526,349526,...,349526,349526,349526,349526,349526,349526,349526,349526,349526,349526
Number of unique entries,56127,42173,28,243,18,2,109,1,1109,5,...,4,1,1050,2,233,53733,1,333,333,11330
List up to 100 unique entries to view the structure of the event attributes,"[4507016139 1, 4507016140 10, 4507016140 20, 4...","[2018-03-14T03:11:00.000000000, 2018-03-14T03:...","[Record Service Entry Sheet, Record Goods Rece...","[227000000000000.0, nan, 228000000000000.0, 22...","[Logistics, Packaging, Sales, CAPEX & SOCS, La...","[Standard PO, Framework order, <NA>]","[Road Packed, Metal Containers & Lids < 30L, L...","[Purchase order, <NA>]","[vendorID_0472, vendorID_0106, vendorID_0103, ...","[Service, Standard, Third-party, Subcontractin...",...,"[NPR, PR, OTHER, undefined, <NA>]","[sourceSystemID_0000, <NA>]","[vendor_0457, vendor_0106, vendor_0103, vendor...","[1, 0]","[1, 10, 20, 30, 100, 40, 50, 60, 70, 80, 90, 1...","[4507016139_00001, 4507016140_00010, 450701614...","[True, <NA>]","[<NA>, batch_07, batch_03, user_029, user_030,...","[<NA>, batch_07, batch_03, user_029, user_030,...","[72.0, 30957.0, 1157.0, 2386.0, 21699.0, 144.0..."
Length of the list of up to 100 unique entries,100,100,29,100,19,3,100,2,100,6,...,5,2,100,2,100,100,2,100,100,100
Number of duplicate entries,293399,307353,349498,349283,349508,349524,349417,349525,348417,349521,...,349522,349525,348476,349524,349293,295793,349525,349193,349193,338196
Number of undefined entries,1495,16078,16078,133,11,11,11,438,11,11,...,11,11,11,0,0,16078,16078,103390,103390,16078
Percentage of undefined entries,0.43,4.60,4.60,0.04,0.00,0.00,0.00,0.13,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,4.60,4.60,29.58,29.58,4.60

In [30]:
# Switching the index of the Meta-DataFrame and table structure
# The current layout of the Meta-Dataframe is transformed, that the columns become the rows, and the rows become the columns.
overview_table = overview_table.T
overview_table.reset_index(inplace = True)
overview_table.rename(columns={'index': 'Property'}, inplace = True)
overview_table

Event log column property,Property,Supplier2_Comparative_Mining,Title,Importance,Level,Data type,Number of entries,Number of unique entries,List up to 100 unique entries to view the structure of the event attributes,Length of the list of up to 100 unique entries,Number of duplicate entries,Number of undefined entries,Percentage of undefined entries
0,caseID,Supplier2_Comparative_Mining,Case ID,Mandatory attribute,Case level,string,349526,56127,"[4507016139 1, 4507016140 10, 4507016140 20, 4...",100,293399,1495,0.43
1,event time:timestamp,Supplier2_Comparative_Mining,Timestamp,Mandatory attribute,Event level,datetime64[ns],349526,42173,"[2018-03-14T03:11:00.000000000, 2018-03-14T03:...",100,307353,16078,4.60
2,event concept:name,Supplier2_Comparative_Mining,Activity,Mandatory attribute,Event level,string,349526,28,"[Record Service Entry Sheet, Record Goods Rece...",29,349498,16078,4.60
3,eventID,Supplier2_Comparative_Mining,eventID,Mandatory attribute,Event level,float64,349526,243,"[227000000000000.0, nan, 228000000000000.0, 22...",100,349283,133,0.04
4,case Spend area text,Supplier2_Comparative_Mining,case Spend area text,Additional attribute,Case level,string,349526,18,"[Logistics, Packaging, Sales, CAPEX & SOCS, La...",19,349508,11,0.00
5,case Document Type,Supplier2_Comparative_Mining,case Document Type,Additional attribute,Case level,string,349526,2,"[Standard PO, Framework order, <NA>]",3,349524,11,0.00
6,case Sub spend area text,Supplier2_Comparative_Mining,case Sub spend area text,Additional attribute,Case level,string,349526,109,"[Road Packed, Metal Containers & Lids < 30L, L...",100,349417,11,0.00
7,case Purch. Doc. Category name,Supplier2_Comparative_Mining,case Purch. Doc. Category name,Additional attribute,Case level,string,349526,1,"[Purchase order, <NA>]",2,349525,438,0.13
8,case Vendor,Supplier2_Comparative_Mining,case Vendor,Additional attribute,Case level,string,349526,1109,"[vendorID_0472, vendorID_0106, vendorID_0103, ...",100,348417,11,0.00
9,case Item Type,Supplier2_Comparative_Mining,case Item Type,Additional attribute,Case level,string,349526,5,"[Service, Standard, Third-party, Subcontractin...",6,349521,11,0.00
10,case Item Category,Supplier2_Comparative_Mining,case Item Category,Additional attribute,Case level,string,349526,3,"[Three way match, invoice after GR, Three way ...",4,349523,784,0.22
11,case Spend classification text,Supplier2_Comparative_Mining,case Spend classification text,Additional attribute,Case level,string,349526,4,"[NPR, PR, OTHER, undefined, <NA>]",5,349522,11,0.00
12,case Source,Supplier2_Comparative_Mining,case Source,Additional attribute,Case level,string,349526,1,"[sourceSystemID_0000, <NA>]",2,349525,11,0.00
13,case Name,Supplier2_Comparative_Mining,case Name,Additional attribute,Case level,string,349526,1050,"[vendor_0457, vendor_0106, vendor_0103, vendor...",100,348476,11,0.00
14,case GR-Based Inv. Verif.,Supplier2_Comparative_Mining,case GR-Based Inv. Verif.,Additional attribute,Case level,int64,349526,2,"[1, 0]",2,349524,0,0.00
15,case Item,Supplier2_Comparative_Mining,case Item,Additional attribute,Case level,int64,349526,233,"[1, 10, 20, 30, 100, 40, 50, 60, 70, 80, 90, 1...",100,349293,0,0.00
16,case concept:name,Supplier2_Comparative_Mining,case concept:name,Additional attribute,Case level,string,349526,53733,"[4507016139_00001, 4507016140_00010, 450701614...",100,295793,16078,4.60
17,case Goods Receipt,Supplier2_Comparative_Mining,case Goods Receipt,Additional attribute,Case level,string,349526,1,"[True, <NA>]",2,349525,16078,4.60
18,event User,Supplier2_Comparative_Mining,event User,Additional attribute,Event level,string,349526,333,"[<NA>, batch_07, batch_03, user_029, user_030,...",100,349193,103390,29.58
19,event org:resource,Supplier2_Comparative_Mining,event org:resource,Additional attribute,Event level,string,349526,333,"[<NA>, batch_07, batch_03, user_029, user_030,...",100,349193,103390,29.58
20,event Cumulative net worth (EUR),Supplier2_Comparative_Mining,event Cumulative net worth (EUR),Additional attribute,Event level,float64,349526,11330,"[72.0, 30957.0, 1157.0, 2386.0, 21699.0, 144.0...",100,338196,16078,4.60

In [31]:
#This is an exploratory code snippet checking for the longest case to model the graph in a deperate database to reveal the event activity sequences in a directly follows graph
case_sizes = event_log_table.groupby(['caseID']).size()
#use of argmax() instead of max()
index_of_longest_case = case_sizes.argmax()
caseID_of_longest_case = case_sizes.index[index_of_longest_case] 
# assert caseID_of_longest_case == '4507000440 10'

# Without the .copy() suffix, we get: A value is trying to be set on a copy of a slice from a DataFrame
case_rows = event_log_table[event_log_table['caseID'] == caseID_of_longest_case].copy()
case_rows.sort_values(by='event time:timestamp', ascending=True, inplace=True)
case_rows.to_csv(f'analysis/longest_case_in_{event_log_name}.csv')

# a csv table is created in the analysis file which is then transformed into Neo4j commands
if not os.path.exists('analysis'):
    os.mkdir('analysis')
overview_table.to_csv(f'analysis/overview_{event_log_name}.csv')

(f'Written: datatype table to analysis/overview_{event_log_name}.csv')

'Written: datatype table to analysis/overview_BPIC_Synthetic_Split_2.csv'

# End of Script 1 to generate the Meta-DataFrame
Author: Kyle Smith <br>
Script: For Masterthesis <br>
University: University of Camerino & University of Applied Sciences Northwestern Switzerland