# First Script: Creating the Meta-DataFrame
In this script the author analyzes each column of the synthetic BPI_C 2019 event logs.

In [1]:
#import libraries
import json
import os
import pandas as pd
import numpy
import re

In [2]:
event_log_name = 'BPIC_Synthetic_Split_3' #addd the name of the event log - change for each event log
event_log_file_path = f'event_logs/{event_log_name}.csv' #string interpolation, one has to create a folder called 'event_logs' to import the event log.csv
print(event_log_file_path) # review the path

event_logs/BPIC_Synthetic_Split_3.csv

In [3]:
#import the event log
event_log_table = pd.read_csv(event_log_file_path) #optionally this can be added; header = 0, encoding = 'ISO-8859-1') if encoding issues arise
event_log_table.head(20) #view the first 20 rows

,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource,event concept:name,event time:timestamp,caseID
0,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
1,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
2,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
3,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
4,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
5,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
6,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
7,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
8,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
9,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
10,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
11,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
12,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:54:00.000,4507032138 1
13,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:54:00.000,4507032138 1
14,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:54:00.000,4507032138 1
15,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:54:00.000,4507032138 1
16,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:54:00.000,4507032138 1
17,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:54:00.000,4507032138 1
18,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:54:00.000,4507032138 1
19,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:54:00.000,4507032138 1

In [4]:
#review changes on the last column
event_log_table

,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource,event concept:name,event time:timestamp,caseID
0,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
1,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
2,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
3,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE,Record Service Entry Sheet,28-05-2018 22:53:00.000,4507032138 1
4,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06,Record Goods Receipt,28-05-2018 22:53:00.000,4507032138 1
...,...,...,...,...,...,...,...,...,...
349522,1.080000e+15,Insurances,2-way match,vendor_1817,False,NONE,Vendor creates invoice,27-08-2018 23:59:00.000,4508076198 150
349523,1.080000e+15,Real estate services,2-way match,vendor_1818,False,NONE,Vendor creates invoice,02-08-2018 23:59:00.000,4508076199 10
349524,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE,Vendor creates invoice,12-01-2018 23:59:00.000,4508076239 10
349525,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE,Vendor creates invoice,12-01-2018 23:59:00.000,4508076239 20
349526,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE,Vendor creates invoice,12-01-2018 23:59:00.000,4508076239 30

In [5]:
#Review all og the event log columns, to decide which ones are mandatory and which ones are additional

log_columns = event_log_table.columns
log_columns # this variable is important for the Meta-DataFrame generation

Index(['eventID ', 'case Sub spend area text', 'case Item Category',
       'case Name', 'case Goods Receipt', 'event org:resource',
       'event concept:name', 'event time:timestamp', 'caseID'],
      dtype='object')

In [6]:
# This has to be tailored to each event log
#caseID is created from 'C_Purchasing Document' and 'case Item', define the mandatory columns based on domain knowledge analysis

mandatory_columns = ['caseID', 'event time:timestamp', 'event concept:name', 'eventID ']

#Create an object/dictionary and corresponding key:value pairs to add the semantic titles which the csv titles represent in a variable  which are relevant for the Meta-DataFrame
titles = {
  'caseID': 'Case ID',
  'event concept:name': 'Activity',
  'eventID ': 'Event ID',
  'event time:timestamp': 'Timestamp',
}

print(mandatory_columns)

['caseID', 'event time:timestamp', 'event concept:name', 'eventID ']

In [7]:
#Review titles object which are relevant for the Meta-DataFrame
titles

{'caseID': 'Case ID',
 'event concept:name': 'Activity',
 'eventID ': 'Event ID',
 'event time:timestamp': 'Timestamp'}

In [8]:
#Review the datatypes for datatype harmonization
event_log_table.dtypes

eventID                     float64
case Sub spend area text     object
case Item Category           object
case Name                    object
case Goods Receipt             bool
event org:resource           object
event concept:name           object
event time:timestamp         object
caseID                       object
dtype: object

In [9]:
#This step is optional to minimize the work needed in harmonization

#Translate object data types of timestamp data into a datetime64[ns] data type for the timestamp. This is a unique datatype from pandas.
timestamp_objects = event_log_table['event time:timestamp'] #declare timestamp to a variable
event_log_table['event time:timestamp']=pd.to_datetime(timestamp_objects)

#Review changes made
#event_log_table['event time:timestamp'].dtypes
event_log_table.dtypes

eventID                            float64
case Sub spend area text            object
case Item Category                  object
case Name                           object
case Goods Receipt                    bool
event org:resource                  object
event concept:name                  object
event time:timestamp        datetime64[ns]
caseID                              object
dtype: object

In [10]:
#This step is optional to minimize the work needed in harmonization 

#Translate object data types of object data types (which contains different possible formats) to a clear string data type format
#for loops where used as they enable somewhat automated transformations 
# = for assigning values
# == operator is used to test equality
for log_column in log_columns:
    if event_log_table[log_column].dtype == 'object': #check if the column has an object data type
        event_log_table[log_column] = event_log_table[log_column].astype('string') #change it to a string

#Review changes
#event_log_table['timestamp'].dtypes
event_log_table.dtypes

eventID                            float64
case Sub spend area text            string
case Item Category                  string
case Name                           string
case Goods Receipt                    bool
event org:resource                  string
event concept:name                  string
event time:timestamp        datetime64[ns]
caseID                              string
dtype: object

In [11]:
# Reorder the columns of the event log table.
# Checking the log columns list contains each item on the mandatory columns list with the assert statement raises an 'AssertionError' if any of the elements are missing. 
# With the delete method and the == operator, the items are removed in the mandatory columns list from the log columns list.
# Then  using the + operator to combine the mandatory columns list and the log columns list (which has been turned into a list using the tolist method). By doing so, a fresh list of columns in # the desired order is created. Using the [] operator to select only the columns in the newly created list, subsetting the event log table DataFrame. By doing this, the columns in the new #DataFrame are created in the desired order.

for mandatory_column in mandatory_columns:
  assert mandatory_column in log_columns 
  log_columns = log_columns.delete(log_columns == mandatory_column)
log_columns = mandatory_columns + log_columns.tolist()

event_log_table = event_log_table[log_columns]
event_log_table #the for loop above resultes in a move of the mandatory columns to the left side (changes order)

,caseID,event time:timestamp,event concept:name,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
0,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
1,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
2,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
3,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
4,4507032138 1,2018-05-28 22:53:00,Record Goods Receipt,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06
...,...,...,...,...,...,...,...,...,...
349522,4508076198 150,2018-08-27 23:59:00,Vendor creates invoice,1.080000e+15,Insurances,2-way match,vendor_1817,False,NONE
349523,4508076199 10,2018-02-08 23:59:00,Vendor creates invoice,1.080000e+15,Real estate services,2-way match,vendor_1818,False,NONE
349524,4508076239 10,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE
349525,4508076239 20,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE
349526,4508076239 30,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE

Here we are going to reset the index and reorder the event log with a new index

Setting the inplace parameter to True and using the reset index method to reset the DataFrame's index. 
This adds a new column to the DataFrame containing the old index values and resets the index to a range of sequential integers beginning at 0. 
Using the rename method and the inplace parameter set to True, rename the column containing the previous index values. 
A dictionary that maps the old column name "index" to the new column name "EventIndex" makes up the columns parameter.
Using the set index method and the inplace parameter set to True, the DataFrame's index is changed to the 'EventIndex' column. 
This will remove the "EventIndex" column from the data and make it the new index of the DataFrame.

In [12]:
# Number every single event in the event log.
# Every single event is represented by a line in the event log file.
event_log_table.reset_index(inplace=True)
event_log_table.rename(columns={'index': 'EventIndex'}, inplace=True)
event_log_table.set_index('EventIndex', inplace=True)

#review changes
event_log_table

/var/folders/vz/snd73j8d2mj817493bt9ykfc0000gn/T/ipykernel_67635/2322881527.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  event_log_table.rename(columns={'index': 'EventIndex'}, inplace=True)

,caseID,event time:timestamp,event concept:name,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
EventIndex,,,,,,,,,
0,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
1,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
2,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
3,4507032138 1,2018-05-28 22:53:00,Record Service Entry Sheet,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,NONE
4,4507032138 1,2018-05-28 22:53:00,Record Goods Receipt,4.690000e+14,Other Logistics Services,"3-way match, invoice after GR",vendor_0225,True,batch_06
...,...,...,...,...,...,...,...,...,...
349522,4508076198 150,2018-08-27 23:59:00,Vendor creates invoice,1.080000e+15,Insurances,2-way match,vendor_1817,False,NONE
349523,4508076199 10,2018-02-08 23:59:00,Vendor creates invoice,1.080000e+15,Real estate services,2-way match,vendor_1818,False,NONE
349524,4508076239 10,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE
349525,4508076239 20,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE
349526,4508076239 30,2018-12-01 23:59:00,Vendor creates invoice,1.080000e+15,Business park,2-way match,vendor_1838,False,NONE

In [13]:
#defining a new dictionary  overview_columns with log columns as the elements
content_overview_columns = [(log_column, ['Supplier2_Comparative_Mining']) for log_column in log_columns]
extra_overview_columns = [('Event log column property', ['Supplier2_Comparative_Mining'])]
overview_columns = dict(extra_overview_columns + content_overview_columns)
overview_table = pd.DataFrame(overview_columns)

# To add a vertically indented name to the index in the console output.
overview_table.set_index('Event log column property', inplace=True)
overview_columns

{'Event log column property': ['Supplier2_Comparative_Mining'],
 'caseID': ['Supplier2_Comparative_Mining'],
 'event time:timestamp': ['Supplier2_Comparative_Mining'],
 'event concept:name': ['Supplier2_Comparative_Mining'],
 'eventID ': ['Supplier2_Comparative_Mining'],
 'case Sub spend area text': ['Supplier2_Comparative_Mining'],
 'case Item Category': ['Supplier2_Comparative_Mining'],
 'case Name': ['Supplier2_Comparative_Mining'],
 'case Goods Receipt': ['Supplier2_Comparative_Mining'],
 'event org:resource': ['Supplier2_Comparative_Mining']}

In [14]:
#view the new overview_table to construct the Meta-DataFrame
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
Event log column property,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining

<h2>Multiple variables based on event data proprocessing which are used for the Meta-DataFrame</h2>

The author uses the pandas .loc function which is an indexer in Pandas is used to choose rows and columns from a DataFrame based on labels.

The snippet below is called title property X as it will be added to the overview table (Meta-DataFrame) with the log columns list's elements as keys and the log column itself as a value, if the title associated with the log column is present in the titles dictionary (if it does not exist in the titles dictionary). 

Then, a new row with the label "Title" and the values from the title property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 

When this code block is run, a new row with the label "Title" and values representing the names of each log column will appear in the overview table DataFrame (or the log column itself if no title is provided).

In [15]:
# Overview for property: Titles - For the Meta-DataFrame
# Depending on whether the title for the log column is present in the titles dictionary, the values of the log columns list are either the log column itself or its associated title (if it does not exist in the titles dictionary).
title_property = {}

for log_column in log_columns:
    if log_column in titles:
        title = titles[log_column]
    else:
        title = log_column
    title_property[log_column] = title


Then, a new row with the label "Title" and the values from the title property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 
When this code block is run, a new row with the label "Title" and values representing the names of each log column will appear in the overview table DataFrame (or the log column itself if no title is provided).

In [16]:
overview_table.loc['Title'] = title_property
overview_table.loc['Title']

caseID                                       Case ID
event time:timestamp                       Timestamp
event concept:name                          Activity
eventID                                     Event ID
case Sub spend area text    case Sub spend area text
case Item Category                case Item Category
case Name                                  case Name
case Goods Receipt                case Goods Receipt
event org:resource                event org:resource
Name: Title, dtype: object

<h2>Dictionary {for mandatory and additional attributes}</h2>

This code block generates a new dictionary called importance property whose keys are the items in the list of log columns and whose values are either "Mandatory attribute" or "Additional attribute" depending on whether the log column is included in the mandatory columns list or not. 
Then, a new row with the label "Importance" and values taken from the importance property dictionary is added to the overview table DataFrame. The assignment will add the new row to the DataFrame, and the.loc indexer will be used to select the row by its label. 
When this code block is run, a new row with the label "Importance" and the values "Mandatory attribute" or "Additional attribute" for each log column, depending on whether that column is in the mandatory columns list or not, will appear in the overview table DataFrame.

The concept is used for other data attributes as well

In [17]:
# Overview property: Label for columns either 'Mandatory attribute' or 'additional_attributes' - For the Meta-DataFrame

importance_property = {}
for log_column in log_columns:
    if log_column in mandatory_columns:
        importance_property[log_column] = 'Mandatory attribute' 
    else:
        importance_property[log_column] = 'Additional attribute'

overview_table.loc['Importance'] = importance_property
overview_table.loc['Importance']

caseID                       Mandatory attribute
event time:timestamp         Mandatory attribute
event concept:name           Mandatory attribute
eventID                      Mandatory attribute
case Sub spend area text    Additional attribute
case Item Category          Additional attribute
case Name                   Additional attribute
case Goods Receipt          Additional attribute
event org:resource          Additional attribute
Name: Importance, dtype: object

The goal of this code snippet is to add a new row to the Meta-Dataframe termed overview table, where the keys are the columns in a list called log columns and the values are strings indicating whether the column is at the "Event level" or the "Case level." The values are determined by examining the column name for the string "event" or "case," respectively.

In [18]:
# Overview property: The level of the event data attribute in the overview table
level_property = {}
for log_column in log_columns:
  if 'event' in log_column:
    level_property[log_column] = 'Event level'
  if 'case' in log_column:
    level_property[log_column] = 'Case level'

overview_table.loc['Level'] = level_property
overview_table.loc['Level']

#NaN's can manually be changed in the Meta-DataFrame

caseID                       Case level
event time:timestamp        Event level
event concept:name          Event level
eventID                     Event level
case Sub spend area text     Case level
case Item Category           Case level
case Name                    Case level
case Goods Receipt           Case level
event org:resource          Event level
Name: Level, dtype: object

In [19]:
# Overview property: Data type
data_type_property = {}
datatypes = event_log_table.dtypes
for log_column in log_columns:
  data_type_property[log_column] = datatypes[log_column]

overview_table.loc['Data type'] = data_type_property

This snippet adds a new row to the Meta-Dataframe in Pandas, with the keys being the columns in a list called log columns and the values being the data types of the corresponding columns in an event log table DataFrame.

In [20]:
# Overview property: Data type
data_type_property = {}
datatypes = event_log_table.dtypes
for log_column in log_columns:
    data_type_property[log_column] = datatypes[log_column]

overview_table.loc['Data type'] = data_type_property
overview_table.loc['Data type']

caseID                              string
event time:timestamp        datetime64[ns]
event concept:name                  string
eventID                            float64
case Sub spend area text            string
case Item Category                  string
case Name                           string
case Goods Receipt                    bool
event org:resource                  string
Name: Data type, dtype: object

In [21]:
# Overview property: Count the number of entries for the Meta-Dataframe
number_of_entries_property = {}
for log_column in log_columns:
    number_of_entries_property[log_column] = len(event_log_table)

overview_table.loc['Number of entries'] = number_of_entries_property
overview_table.loc['Number of entries']

caseID                      349527
event time:timestamp        349527
event concept:name          349527
eventID                     349527
case Sub spend area text    349527
case Item Category          349527
case Name                   349527
case Goods Receipt          349527
event org:resource          349527
Name: Number of entries, dtype: object

In [22]:
# Overview property: Number of unique entries
number_of_unique_entries_property = {}
for log_column in log_columns:
  count = event_log_table[log_column].value_counts().count()
  number_of_unique_entries_property[log_column] = count

overview_table.loc['Number of unique entries'] = number_of_unique_entries_property
overview_table.loc['Number of unique entries']

caseID                      70874
event time:timestamp        42245
event concept:name             27
eventID                       362
case Sub spend area text      121
case Item Category              4
case Name                    1262
case Goods Receipt              2
event org:resource            425
Name: Number of unique entries, dtype: object

In [23]:
#Overview property: List of up to 100 unique entries (to grasp an understanding of how the data looks and it is structured and not just metrics)
unique_entries_property = {}
for log_column in log_columns:
    unique_entries = event_log_table[log_column].unique()
    unique_entries = list(unique_entries)
    unique_entries = unique_entries[:100]
    unique_entries_property[log_column] = unique_entries

overview_table.loc['List up to 100 unique entries to view the structure of the event attributes']= unique_entries_property
unique_entries_property

{'caseID': ['4507032138 1',
  '4507032139 1',
  '4507032140 1',
  '4507032141 1',
  '4507032142 1',
  '4507032143 1',
  '4507032144 1',
  '4507032145 1',
  '4507032146 1',
  '4507032147 1',
  '4507032148 1',
  '4507032149 10',
  '4507032150 10',
  '4507032150 20',
  '4507032150 30',
  '4507032150 40',
  '4507032150 50',
  '4507032150 60',
  '4507032151 10',
  '4507032151 20',
  '4507032151 30',
  '4507032152 10',
  '4507032152 20',
  '4507032153 10',
  '4507032153 100',
  '4507032153 110',
  '4507032153 120',
  '4507032153 130',
  '4507032153 140',
  '4507032153 20',
  '4507032153 30',
  '4507032153 40',
  '4507032153 50',
  '4507032153 60',
  '4507032153 70',
  '4507032153 80',
  '4507032153 90',
  '4507032154 10',
  '4507032154 20',
  '4507032155 10',
  '4507032155 20',
  '4507032155 30',
  '4507032155 40',
  '4507032156 10',
  '4507032157 10',
  '4507032157 100',
  '4507032157 110',
  '4507032157 120',
  '4507032157 130',
  '4507032157 140',
  '4507032157 150',
  '4507032157 160',
  '4507032157 170',
  '4507032157 180',
  '4507032157 190',
  '4507032157 20',
  '4507032157 200',
  '4507032157 210',
  '4507032157 220',
  '4507032157 230',
  '4507032157 240',
  '4507032157 250',
  '4507032157 260',
  '4507032157 270',
  '4507032157 280',
  '4507032157 290',
  '4507032157 30',
  '4507032157 300',
  '4507032157 310',
  '4507032157 320',
  '4507032157 330',
  '4507032157 340',
  '4507032157 350',
  '4507032157 360',
  '4507032157 370',
  '4507032157 380',
  '4507032157 390',
  '4507032157 40',
  '4507032157 400',
  '4507032157 410',
  '4507032157 420',
  '4507032157 430',
  '4507032157 440',
  '4507032157 450',
  '4507032157 460',
  '4507032157 470',
  '4507032157 480',
  '4507032157 490',
  '4507032157 50',
  '4507032157 500',
  '4507032157 510',
  '4507032157 520',
  '4507032157 530',
  '4507032157 540',
  '4507032157 550',
  '4507032157 560',
  '4507032157 570',
  '4507032157 60',
  '4507032157 70',
  '4507032157 80'],
 'event time:timestamp': [numpy.datetime64('2018-05-28T22:53:00.000000000'),
  numpy.datetime64('2018-05-28T22:54:00.000000000'),
  numpy.datetime64('2018-05-28T22:55:00.000000000'),
  numpy.datetime64('2018-05-31T23:59:00.000000000'),
  numpy.datetime64('2018-06-06T11:52:00.000000000'),
  numpy.datetime64('2018-09-08T14:30:00.000000000'),
  numpy.datetime64('2018-05-28T22:44:00.000000000'),
  numpy.datetime64('2018-05-28T22:45:00.000000000'),
  numpy.datetime64('2018-08-06T23:59:00.000000000'),
  numpy.datetime64('2018-08-16T10:29:00.000000000'),
  numpy.datetime64('2018-06-09T14:09:00.000000000'),
  numpy.datetime64('2018-05-28T22:50:00.000000000'),
  numpy.datetime64('2018-07-18T13:27:00.000000000'),
  numpy.datetime64('2018-07-18T16:03:00.000000000'),
  numpy.datetime64('2018-05-06T23:59:00.000000000'),
  numpy.datetime64('2018-08-29T15:58:00.000000000'),
  numpy.datetime64('2018-05-28T23:01:00.000000000'),
  numpy.datetime64('2018-05-28T23:03:00.000000000'),
  numpy.datetime64('2018-05-28T23:04:00.000000000'),
  numpy.datetime64('2018-05-28T23:05:00.000000000'),
  numpy.datetime64('2018-05-29T23:00:00.000000000'),
  numpy.datetime64('2018-05-28T23:02:00.000000000'),
  numpy.datetime64('2018-05-28T23:30:00.000000000'),
  numpy.datetime64('2018-05-28T23:31:00.000000000'),
  numpy.datetime64('2018-05-28T23:33:00.000000000'),
  numpy.datetime64('2018-05-28T23:35:00.000000000'),
  numpy.datetime64('2018-05-28T23:38:00.000000000'),
  numpy.datetime64('2018-05-28T23:40:00.000000000'),
  numpy.datetime64('2018-05-28T23:44:00.000000000'),
  numpy.datetime64('2018-05-28T23:45:00.000000000'),
  numpy.datetime64('2018-05-28T23:50:00.000000000'),
  numpy.datetime64('2018-05-28T23:53:00.000000000'),
  numpy.datetime64('2018-05-28T23:54:00.000000000'),
  numpy.datetime64('2018-05-28T23:46:00.000000000'),
  numpy.datetime64('2018-05-28T23:47:00.000000000'),
  numpy.datetime64('2018-05-29T00:31:00.000000000'),
  numpy.datetime64('2018-06-15T23:59:00.000000000'),
  numpy.datetime64('2018-06-20T11:35:00.000000000'),
  numpy.datetime64('2018-06-26T13:16:00.000000000'),
  numpy.datetime64('2018-09-08T14:28:00.000000000'),
  numpy.datetime64('2018-05-29T00:32:00.000000000'),
  numpy.datetime64('2018-06-06T13:25:00.000000000'),
  numpy.datetime64('2018-06-18T08:48:00.000000000'),
  numpy.datetime64('2018-07-06T23:59:00.000000000'),
  numpy.datetime64('2018-11-06T15:10:00.000000000'),
  numpy.datetime64('2018-06-18T09:25:00.000000000'),
  numpy.datetime64('2018-06-18T17:58:00.000000000'),
  numpy.datetime64('2018-06-09T14:06:00.000000000'),
  numpy.datetime64('2018-01-06T13:43:00.000000000'),
  numpy.datetime64('2018-12-06T07:55:00.000000000'),
  numpy.datetime64('2018-05-30T23:59:00.000000000'),
  numpy.datetime64('2018-06-09T17:26:00.000000000'),
  numpy.datetime64('2018-05-29T00:33:00.000000000'),
  numpy.datetime64('2018-05-31T17:07:00.000000000'),
  numpy.datetime64('2018-07-06T12:31:00.000000000'),
  numpy.datetime64('2018-06-14T14:15:00.000000000'),
  numpy.datetime64('2018-07-19T10:21:00.000000000'),
  numpy.datetime64('2018-06-06T23:59:00.000000000'),
  numpy.datetime64('2018-07-06T17:15:00.000000000'),
  numpy.datetime64('2018-06-07T09:47:00.000000000'),
  numpy.datetime64('2018-08-23T12:58:00.000000000'),
  numpy.datetime64('2018-06-30T23:59:00.000000000'),
  numpy.datetime64('2018-04-07T14:15:00.000000000'),
  numpy.datetime64('2018-05-07T17:33:00.000000000'),
  numpy.datetime64('2018-11-07T14:17:00.000000000'),
  numpy.datetime64('2018-07-26T18:06:00.000000000'),
  numpy.datetime64('2018-05-29T00:34:00.000000000'),
  numpy.datetime64('2018-01-06T12:10:00.000000000'),
  numpy.datetime64('2018-11-06T23:59:00.000000000'),
  numpy.datetime64('2018-12-06T09:25:00.000000000'),
  numpy.datetime64('2018-08-17T11:53:00.000000000'),
  numpy.datetime64('2018-06-18T08:25:00.000000000'),
  numpy.datetime64('2018-06-22T11:30:00.000000000'),
  numpy.datetime64('2018-07-19T13:40:00.000000000'),
  numpy.datetime64('2018-06-29T15:55:00.000000000'),
  numpy.datetime64('2018-06-07T15:58:00.000000000'),
  numpy.datetime64('2018-07-20T23:59:00.000000000'),
  numpy.datetime64('2018-07-26T07:09:00.000000000'),
  numpy.datetime64('2018-07-26T17:52:00.000000000'),
  numpy.datetime64('2018-08-30T15:37:00.000000000'),
  numpy.datetime64('2018-05-29T00:35:00.000000000'),
  numpy.datetime64('2018-07-23T13:35:00.000000000'),
  numpy.datetime64('2018-09-07T13:45:00.000000000'),
  numpy.datetime64('2018-10-07T23:59:00.000000000'),
  numpy.datetime64('2018-06-20T11:25:00.000000000'),
  numpy.datetime64('2018-06-21T23:59:00.000000000'),
  numpy.datetime64('2018-06-14T23:59:00.000000000'),
  numpy.datetime64('2018-06-15T13:13:00.000000000'),
  numpy.datetime64('2018-06-18T13:15:00.000000000'),
  numpy.datetime64('2018-06-19T02:17:00.000000000'),
  numpy.datetime64('2018-05-29T00:40:00.000000000'),
  numpy.datetime64('2018-06-06T10:15:00.000000000'),
  numpy.datetime64('2018-07-20T10:17:00.000000000'),
  numpy.datetime64('2018-08-30T15:39:00.000000000'),
  numpy.datetime64('2018-06-18T23:59:00.000000000'),
  numpy.datetime64('2018-06-19T10:45:00.000000000'),
  numpy.datetime64('2018-06-08T16:13:00.000000000'),
  numpy.datetime64('2018-07-08T16:57:00.000000000'),
  numpy.datetime64('2018-06-21T13:25:00.000000000'),
  numpy.datetime64('2018-01-08T08:35:00.000000000')],
 'event concept:name': ['Record Service Entry Sheet',
  'Record Goods Receipt',
  'Vendor creates invoice',
  'Record Invoice Receipt',
  'Clear Invoice',
  'Create Purchase Order Item',
  'Delete Purchase Order Item',
  'Remove Payment Block',
  'Change Delivery Indicator',
  'Change Quantity',
  'Vendor creates debit memo',
  'Cancel Invoice Receipt',
  'Receive Order Confirmation',
  'Change Price',
  'Create Purchase Requisition Item',
  'Cancel Goods Receipt',
  'Reactivate Purchase Order Item',
  'Update Order Confirmation',
  'Change Approval for Purchase Order',
  'Record Subsequent Invoice',
  'Cancel Subsequent Invoice',
  'Change Storage Location',
  'Block Purchase Order Item',
  'Release Purchase Order',
  'Set Payment Block',
  'Change payment term',
  'Change Currency'],
 'eventID ': [469000000000000.0,
  470000000000000.0,
  471000000000000.0,
  472000000000000.0,
  473000000000000.0,
  474000000000000.0,
  475000000000000.0,
  476000000000000.0,
  477000000000000.0,
  478000000000000.0,
  479000000000000.0,
  480000000000000.0,
  481000000000000.0,
  482000000000000.0,
  483000000000000.0,
  484000000000000.0,
  485000000000000.0,
  486000000000000.0,
  487000000000000.0,
  488000000000000.0,
  489000000000000.0,
  490000000000000.0,
  491000000000000.0,
  492000000000000.0,
  493000000000000.0,
  494000000000000.0,
  495000000000000.0,
  496000000000000.0,
  497000000000000.0,
  498000000000000.0,
  499000000000000.0,
  500000000000000.0,
  501000000000000.0,
  502000000000000.0,
  503000000000000.0,
  504000000000000.0,
  505000000000000.0,
  506000000000000.0,
  507000000000000.0,
  508000000000000.0,
  509000000000000.0,
  510000000000000.0,
  511000000000000.0,
  512000000000000.0,
  513000000000000.0,
  514000000000000.0,
  515000000000000.0,
  516000000000000.0,
  517000000000000.0,
  518000000000000.0,
  519000000000000.0,
  520000000000000.0,
  521000000000000.0,
  522000000000000.0,
  523000000000000.0,
  524000000000000.0,
  525000000000000.0,
  526000000000000.0,
  527000000000000.0,
  528000000000000.0,
  529000000000000.0,
  530000000000000.0,
  531000000000000.0,
  532000000000000.0,
  533000000000000.0,
  534000000000000.0,
  535000000000000.0,
  536000000000000.0,
  537000000000000.0,
  538000000000000.0,
  539000000000000.0,
  540000000000000.0,
  541000000000000.0,
  542000000000000.0,
  543000000000000.0,
  544000000000000.0,
  545000000000000.0,
  546000000000000.0,
  547000000000000.0,
  548000000000000.0,
  549000000000000.0,
  550000000000000.0,
  551000000000000.0,
  552000000000000.0,
  553000000000000.0,
  554000000000000.0,
  555000000000000.0,
  556000000000000.0,
  557000000000000.0,
  558000000000000.0,
  559000000000000.0,
  560000000000000.0,
  561000000000000.0,
  562000000000000.0,
  563000000000000.0,
  564000000000000.0,
  565000000000000.0,
  566000000000000.0,
  567000000000000.0,
  568000000000000.0],
 'case Sub spend area text': ['Other Logistics Services',
  'Road Packed',
  'Sea',
  'Metal Containers & Lids < 30L',
  'Labels',
  'Packaging - Other',
  'Plastic Containers & Lids < 30L',
  'Intermediate Bulk Containers (IBC)',
  'Hybrid Containers',
  'Packaging',
  'Closures',
  'Products for Resale',
  'Customers',
  'Latexes - Other',
  'Driers & Antiskinning Agents',
  'Catalysts & Initiators',
  'Extenders',
  'Sulphate',
  'Styrene Acrylics',
  'Alkyd Resins',
  'Colorants',
  'Aliphatic Solvents',
  'Business Gifts & Promotional Items',
  'Trading products (old structure)',
  'Laboratory Supplies & Services',
  'Equipment',
  'Raw Material',
  'MRO (components)',
  'Pure Acrylics',
  'Light & Heat Stabilizers',
  'Paperboard',
  <NA>,
  'Plastic Film',
  'Point of Sales',
  'Surfactants',
  'Biocides',
  'Defoamers & Antifoams',
  'Vinyl Acetate Ethylenes',
  'Vinyl Acrylics',
  'Chloride',
  'Opaque Polymers',
  'Rheology & Thixotropic Agents',
  'Ester Solvents',
  'Additives - Other',
  'Polyurethane Resins',
  'Isocyanates',
  'Pigments - Other',
  'Commodity Resins Precursors',
  'Corrosion Inhibitors',
  'Commercial Printing',
  'Glycol & Ether Solvents',
  'Drums',
  'Waxes',
  'Process Automation & Instrumentation',
  'Specialty Resins - Other',
  'Effect Pigments',
  'Plasticizers',
  'Facility Management',
  'Polyamides & Polyamines',
  'Specialty Resins Precursors',
  'Ketones Solvents',
  'Utilities',
  'Color Collateral',
  'Alcohol Solvents',
  'Mixing Machines',
  'Neutralisation Agents',
  'Inorganic Pigments',
  'Pallets',
  'Polyester Resins - Liquid',
  'Transport & Hoisting Equipment',
  'UV Resins',
  'Epoxy Resins - Liquid',
  'ICT Hardware',
  'Monomers - Hydroxy',
  'Amino Resins',
  'Epoxy Resins - Solid',
  'Office Supplies',
  'Technical Services',
  'Bottles',
  'Tubes',
  'Sachets',
  'Bags',
  'QHSE Services',
  'Aromatic Solvents',
  'Carbon Black Pigments',
  'Gasses',
  'Acrylic Resins ¬ñ Liquid',
  'Solvents - Other',
  'Organic Pigments',
  'Design',
  'Jerry Cans',
  'Adhesion Promotors',
  'Cartridges',
  'Advertising',
  'Monomers - Styrene',
  'HR Services',
  'Polyvinyl Acetates',
  'Semi-Finished Materials',
  'Exhibitions & seminars',
  'Sales Promotion'],
 'case Item Category': ['3-way match, invoice after GR',
  'Consignment',
  '3-way match, invoice before GR',
  '2-way match'],
 'case Name': ['vendor_0225',
  'vendor_0226',
  'vendor_0228',
  'vendor_0455',
  'vendor_0353',
  'vendor_0354',
  'vendor_0352',
  'vendor_0355',
  'vendor_0229',
  'vendor_0230',
  'vendor_0490',
  'vendor_0173',
  'vendor_0135',
  'vendor_0124',
  'vendor_0119',
  'vendor_0267',
  'vendor_0165',
  'vendor_0103',
  'vendor_0257',
  'vendor_0508',
  'vendor_0506',
  'vendor_0750',
  'vendor_0509',
  'vendor_0679',
  'vendor_0192',
  'vendor_0507',
  'vendor_0483',
  'vendor_0457',
  'vendor_0458',
  'vendor_0456',
  'vendor_0104',
  'vendor_0106',
  'vendor_0639',
  'vendor_0115',
  'vendor_0519',
  'vendor_0525',
  'vendor_0156',
  'vendor_0591',
  'vendor_0305',
  'vendor_0396',
  'vendor_0592',
  'vendor_0143',
  'vendor_0769',
  'vendor_0410',
  'vendor_0260',
  'vendor_0062',
  'vendor_0169',
  'vendor_0522',
  'vendor_0249',
  'vendor_0233',
  'vendor_0367',
  'vendor_0117',
  'vendor_0121',
  'vendor_0122',
  'vendor_1372',
  'vendor_1084',
  'vendor_0954',
  'vendor_0360',
  'vendor_0371',
  'vendor_0269',
  'vendor_0108',
  'vendor_0462',
  'vendor_0585',
  'vendor_0361',
  'vendor_0110',
  'vendor_0363',
  'vendor_0586',
  'vendor_0157',
  'vendor_0137',
  'vendor_0111',
  'vendor_1231',
  'vendor_0718',
  'vendor_0219',
  'vendor_1407',
  'vendor_0164',
  'vendor_0263',
  'vendor_0194',
  'vendor_0281',
  'vendor_0134',
  'vendor_0416',
  'vendor_0753',
  'vendor_0896',
  'vendor_0181',
  'vendor_0290',
  'vendor_0566',
  'vendor_0567',
  'vendor_0189',
  'vendor_0437',
  'vendor_1249',
  'vendor_0382',
  'vendor_0270',
  'vendor_0439',
  'vendor_0388',
  'vendor_0804',
  'vendor_0176',
  'vendor_0802',
  'vendor_0278',
  'vendor_0306',
  'vendor_0707',
  'vendor_0475'],
 'case Goods Receipt': [True, False],
 'event org:resource': ['NONE',
  'batch_06',
  'user_013',
  'user_002',
  'user_001',
  'user_012',
  'batch_10',
  'batch_02',
  'user_147',
  'user_020',
  'user_019',
  'user_023',
  'user_015',
  'user_286',
  'user_235',
  'batch_00',
  'batch_07',
  'batch_03',
  'user_059',
  'user_029',
  'user_062',
  'user_065',
  'batch_04',
  'user_060',
  'user_031',
  'user_038',
  'user_070',
  'user_200',
  'user_068',
  'user_058',
  'user_148',
  'user_168',
  'user_133',
  'user_004',
  'user_124',
  'user_119',
  'user_080',
  'user_126',
  'user_040',
  'user_042',
  'user_041',
  'user_007',
  'user_236',
  'user_208',
  'user_078',
  'user_077',
  'user_036',
  'user_326',
  'user_063',
  'user_045',
  'user_047',
  'user_049',
  'user_275',
  'user_263',
  'user_104',
  'user_071',
  'user_142',
  'user_158',
  'user_030',
  'user_135',
  'batch_05',
  'user_056',
  'user_097',
  'user_037',
  'user_277',
  'user_120',
  'user_181',
  'user_057',
  'user_034',
  'user_176',
  'user_137',
  'user_144',
  'user_098',
  'user_027',
  'user_184',
  'user_171',
  'user_087',
  'user_066',
  'user_053',
  'user_086',
  'user_112',
  'user_363',
  'user_115',
  'user_367',
  'user_186',
  'user_167',
  'user_102',
  'user_006',
  'user_178',
  'user_152',
  'user_197',
  'user_127',
  'user_094',
  'user_194',
  'user_089',
  'user_046',
  'user_257',
  'user_082',
  'user_067',
  'user_327']}

In [24]:
# Overview property: Length of the list of up to 100 unique entries
num_displayed_unique_entries_property = {}
for log_column in log_columns:
  unique_entries = event_log_table[log_column].unique()
  unique_entries = list(unique_entries)
  unique_entries = unique_entries[:100]
  num_displayed_unique_entries_property[log_column] = len(unique_entries)

overview_table.loc['Length of the list of up to 100 unique entries'] = num_displayed_unique_entries_property
num_displayed_unique_entries_property

{'caseID': 100,
 'event time:timestamp': 100,
 'event concept:name': 27,
 'eventID ': 100,
 'case Sub spend area text': 100,
 'case Item Category': 4,
 'case Name': 100,
 'case Goods Receipt': 2,
 'event org:resource': 100}

In [25]:
# Inspect the overview table
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
Event log column property,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining
Title,Case ID,Timestamp,Activity,Event ID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
Importance,Mandatory attribute,Mandatory attribute,Mandatory attribute,Mandatory attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute
Level,Case level,Event level,Event level,Event level,Case level,Case level,Case level,Case level,Event level
Data type,string,datetime64[ns],string,float64,string,string,string,bool,string
Number of entries,349527,349527,349527,349527,349527,349527,349527,349527,349527
Number of unique entries,70874,42245,27,362,121,4,1262,2,425
List up to 100 unique entries to view the structure of the event attributes,"[4507032138 1, 4507032139 1, 4507032140 1, 450...","[2018-05-28T22:53:00.000000000, 2018-05-28T22:...","[Record Service Entry Sheet, Record Goods Rece...","[469000000000000.0, 470000000000000.0, 4710000...","[Other Logistics Services, Road Packed, Sea, M...","[3-way match, invoice after GR, Consignment, 3...","[vendor_0225, vendor_0226, vendor_0228, vendor...","[True, False]","[NONE, batch_06, user_013, user_002, user_001,..."
Length of the list of up to 100 unique entries,100,100,27,100,100,4,100,2,100

In [26]:
# Overview property: Number of duplicate entries
number_of_duplicate_entries_property = {}
for log_column in log_columns:
  number_of_duplicate_entries_property[log_column] = number_of_entries_property[log_column] - number_of_unique_entries_property[log_column]

overview_table.loc['Number of duplicate entries'] = number_of_duplicate_entries_property
overview_table.loc['Number of duplicate entries']

caseID                      278653
event time:timestamp        307282
event concept:name          349500
eventID                     349165
case Sub spend area text    349406
case Item Category          349523
case Name                   348265
case Goods Receipt          349525
event org:resource          349102
Name: Number of duplicate entries, dtype: object

In [27]:
# Overview property: Number of undefined entries
number_of_undefined_entries_property = {}
nan_info = event_log_table.isna().sum()
for log_column in log_columns:
    number_of_undefined_entries_property[log_column] = nan_info[log_column]

overview_table.loc['Number of undefined entries'] = number_of_undefined_entries_property
number_of_undefined_entries_property

{'caseID': 0,
 'event time:timestamp': 0,
 'event concept:name': 0,
 'eventID ': 0,
 'case Sub spend area text': 2352,
 'case Item Category': 0,
 'case Name': 0,
 'case Goods Receipt': 0,
 'event org:resource': 0}

In [28]:
# Overview propperty: Number of undefined entries in percentages
percentage_of_undefined_entries_property = {}
nan_info = event_log_table.isna().sum()
for log_column in log_columns:
    percentage = nan_info[log_column]/len(event_log_table)*100 #len calculates the length of a variable
    percentage = f'{percentage:.2f}'
    percentage_of_undefined_entries_property[log_column] = percentage

overview_table.loc['Percentage of undefined entries'] = percentage_of_undefined_entries_property
percentage_of_undefined_entries_property

{'caseID': '0.00',
 'event time:timestamp': '0.00',
 'event concept:name': '0.00',
 'eventID ': '0.00',
 'case Sub spend area text': '0.67',
 'case Item Category': '0.00',
 'case Name': '0.00',
 'case Goods Receipt': '0.00',
 'event org:resource': '0.00'}

In [29]:
overview_table

,caseID,event time:timestamp,event concept:name,eventID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
Event log column property,,,,,,,,,
Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining,Supplier2_Comparative_Mining
Title,Case ID,Timestamp,Activity,Event ID,case Sub spend area text,case Item Category,case Name,case Goods Receipt,event org:resource
Importance,Mandatory attribute,Mandatory attribute,Mandatory attribute,Mandatory attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute,Additional attribute
Level,Case level,Event level,Event level,Event level,Case level,Case level,Case level,Case level,Event level
Data type,string,datetime64[ns],string,float64,string,string,string,bool,string
Number of entries,349527,349527,349527,349527,349527,349527,349527,349527,349527
Number of unique entries,70874,42245,27,362,121,4,1262,2,425
List up to 100 unique entries to view the structure of the event attributes,"[4507032138 1, 4507032139 1, 4507032140 1, 450...","[2018-05-28T22:53:00.000000000, 2018-05-28T22:...","[Record Service Entry Sheet, Record Goods Rece...","[469000000000000.0, 470000000000000.0, 4710000...","[Other Logistics Services, Road Packed, Sea, M...","[3-way match, invoice after GR, Consignment, 3...","[vendor_0225, vendor_0226, vendor_0228, vendor...","[True, False]","[NONE, batch_06, user_013, user_002, user_001,..."
Length of the list of up to 100 unique entries,100,100,27,100,100,4,100,2,100
Number of duplicate entries,278653,307282,349500,349165,349406,349523,348265,349525,349102
Number of undefined entries,0,0,0,0,2352,0,0,0,0
Percentage of undefined entries,0.00,0.00,0.00,0.00,0.67,0.00,0.00,0.00,0.00

In [30]:
# Switching the index of the Meta-DataFrame and table structure
# The current layout of the Meta-Dataframe is transformed, that the columns become the rows, and the rows become the columns.
overview_table = overview_table.T
overview_table.reset_index(inplace = True)
overview_table.rename(columns={'index': 'Property'}, inplace = True)
overview_table

Event log column property,Property,Supplier2_Comparative_Mining,Title,Importance,Level,Data type,Number of entries,Number of unique entries,List up to 100 unique entries to view the structure of the event attributes,Length of the list of up to 100 unique entries,Number of duplicate entries,Number of undefined entries,Percentage of undefined entries
0,caseID,Supplier2_Comparative_Mining,Case ID,Mandatory attribute,Case level,string,349527,70874,"[4507032138 1, 4507032139 1, 4507032140 1, 450...",100,278653,0,0.00
1,event time:timestamp,Supplier2_Comparative_Mining,Timestamp,Mandatory attribute,Event level,datetime64[ns],349527,42245,"[2018-05-28T22:53:00.000000000, 2018-05-28T22:...",100,307282,0,0.00
2,event concept:name,Supplier2_Comparative_Mining,Activity,Mandatory attribute,Event level,string,349527,27,"[Record Service Entry Sheet, Record Goods Rece...",27,349500,0,0.00
3,eventID,Supplier2_Comparative_Mining,Event ID,Mandatory attribute,Event level,float64,349527,362,"[469000000000000.0, 470000000000000.0, 4710000...",100,349165,0,0.00
4,case Sub spend area text,Supplier2_Comparative_Mining,case Sub spend area text,Additional attribute,Case level,string,349527,121,"[Other Logistics Services, Road Packed, Sea, M...",100,349406,2352,0.67
5,case Item Category,Supplier2_Comparative_Mining,case Item Category,Additional attribute,Case level,string,349527,4,"[3-way match, invoice after GR, Consignment, 3...",4,349523,0,0.00
6,case Name,Supplier2_Comparative_Mining,case Name,Additional attribute,Case level,string,349527,1262,"[vendor_0225, vendor_0226, vendor_0228, vendor...",100,348265,0,0.00
7,case Goods Receipt,Supplier2_Comparative_Mining,case Goods Receipt,Additional attribute,Case level,bool,349527,2,"[True, False]",2,349525,0,0.00
8,event org:resource,Supplier2_Comparative_Mining,event org:resource,Additional attribute,Event level,string,349527,425,"[NONE, batch_06, user_013, user_002, user_001,...",100,349102,0,0.00

In [31]:
#This is an exploratory code snippet checking for the longest case to model the graph in a deperate database to reveal the event activity sequences in a directly follows graph
case_sizes = event_log_table.groupby(['caseID']).size()
#use of argmax() instead of max()
index_of_longest_case = case_sizes.argmax()
caseID_of_longest_case = case_sizes.index[index_of_longest_case] 

# Without the .copy() suffix, we get: A value is trying to beset on a copy of a slice from a DataFrame
case_rows = event_log_table[event_log_table['caseID'] == caseID_of_longest_case].copy()
case_rows.sort_values(by='event time:timestamp', ascending=True, inplace=True)
case_rows.to_csv(f'analysis/longest_case_in_{event_log_name}.csv')

# a csv table is created in the analysis file which is then transformed into Neo4j commands
if not os.path.exists('analysis'):
    os.mkdir('analysis')
overview_table.to_csv(f'analysis/overview_{event_log_name}.csv')

(f'Written: datatype table to analysis/overview_{event_log_name}.csv')

'Written: datatype table to analysis/overview_BPIC_Synthetic_Split_3.csv'

# End of Script 1 to generate the Meta-DataFrame
Author: Kyle Smith <br>
Script: For Masterthesis <br>
University: University of Camerino & University of Applied Sciences Northwestern Switzerland